import { randomUUID } from "expo-crypto";
import { assertUuid, branchPath, organizationPath, type ApiClient } from "@salekhpos/packages-api-client";
import { CommerceContractError, parseLoyaltyAccount, parseLoyaltyAccountPage, parseLoyaltyPointsResult, parsePromotion, parsePromotionEvaluation, parsePromotionPage, parseStockTransfer, parseStockTransferPage, type LoyaltyAccount, type Promotion, type StockTransfer } from "@/api/commerceContracts";

function required<T>(value:T|undefined):T{if(value===undefined)throw new CommerceContractError("response");return value}
function pageSize(value:number){if(!Number.isInteger(value)||value<1||value>100)throw new TypeError("Page size is invalid.");return value}
function clean(value:string,max:number,label:string){const v=value.trim();if(!v||v.length>max||/[\u0000-\u001f\u007f]/u.test(v))throw new TypeError(`${label} is invalid.`);return v}
function money(value:number,label:string,min=0){if(!Number.isFinite(value)||value<min||Math.abs(value)>1e15)throw new TypeError(`${label} is invalid.`);return value}
function currency(value:string){const v=value.trim().toUpperCase();if(!/^[A-Z]{3}$/u.test(v))throw new TypeError("Currency is invalid.");return v}

export function createCommerceExtensions(client:ApiClient){return Object.freeze({
 async listTransfers(org:string,branch:string,size=100,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId");const r=parseStockTransferPage(required(await client.get<unknown>(branchPath(o,b,"stock-transfers"),{query:{pageSize:pageSize(size)},...(signal?{signal}:{})})));if(r.items.some(x=>x.sourceBranchId!==b&&x.destinationBranchId!==b))throw new CommerceContractError("transfers");return r;},
 async createTransfer(org:string,branch:string,input:{destinationBranchId:string;reference?:string;lines:readonly {productId:string;quantity:number}[]},signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId"),destinationBranchId=assertUuid(input.destinationBranchId,"destinationBranchId");if(destinationBranchId===b||input.lines.length<1||input.lines.length>500)throw new TypeError("Transfer is invalid.");const lines=input.lines.map(x=>({productId:assertUuid(x.productId,"productId"),quantity:money(x.quantity,"quantity",Number.EPSILON)}));const r=parseStockTransfer(required(await client.post<unknown>(branchPath(o,b,"stock-transfers"),{body:{destinationBranchId,reference:input.reference?.trim()||null,lines},idempotencyKey:randomUUID(),...(signal?{signal}:{})})));if(r.sourceBranchId!==b||r.destinationBranchId!==destinationBranchId)throw new CommerceContractError("transfer");return r;},
 async changeTransfer(org:string,branch:string,transfer:StockTransfer,action:"dispatch"|"receive"|"cancel",signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId"),id=assertUuid(transfer.id,"transferId");const r=parseStockTransfer(required(await client.post<unknown>(branchPath(o,b,"stock-transfers",id,action),{body:{expectedVersion:transfer.version},...(signal?{signal}:{})})));if(r.id!==id||(r.sourceBranchId!==b&&r.destinationBranchId!==b))throw new CommerceContractError("transfer");return r;},
 async listPromotions(org:string,branch:string,size=100,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId");const r=parsePromotionPage(required(await client.get<unknown>(branchPath(o,b,"promotions"),{query:{pageSize:pageSize(size)},...(signal?{signal}:{})})));if(r.items.some(x=>x.branchId!==null&&x.branchId!==b))throw new CommerceContractError("promotions");return r;},
 async createPromotion(org:string,branch:string,input:{code:string;name:string;discountKind:"percentage"|"fixed";value:number;currency?:string;minimumSubtotal:number;startsAt:string;endsAt?:string},signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId");const body={code:clean(input.code,40,"Code").toUpperCase(),name:clean(input.name,160,"Name"),branchId:b,discountKind:input.discountKind,value:money(input.value,"Value",Number.EPSILON),currency:input.discountKind==="fixed"?currency(input.currency??""):null,minimumSubtotal:money(input.minimumSubtotal,"Minimum subtotal"),startsAt:new Date(input.startsAt).toISOString(),endsAt:input.endsAt?new Date(input.endsAt).toISOString():null};return parsePromotion(required(await client.post<unknown>(branchPath(o,b,"promotions"),{body,idempotencyKey:randomUUID(),...(signal?{signal}:{})})));},
 async deactivatePromotion(org:string,branch:string,promotion:Promotion,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId"),id=assertUuid(promotion.id,"promotionId");return parsePromotion(required(await client.post<unknown>(branchPath(o,b,"promotions",id,"deactivate"),{body:{expectedVersion:promotion.version},...(signal?{signal}:{})})));},
 async evaluatePromotion(org:string,branch:string,subtotal:number,currencyCode:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),b=assertUuid(branch,"branchId");return parsePromotionEvaluation(required(await client.post<unknown>(branchPath(o,b,"promotions","evaluate"),{body:{subtotal:money(subtotal,"Subtotal"),currency:currency(currencyCode),at:new Date().toISOString()},...(signal?{signal}:{})})));},
 async listLoyaltyAccounts(org:string,size=100,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseLoyaltyAccountPage(required(await client.get<unknown>(organizationPath(o,"loyalty","accounts"),{query:{pageSize:pageSize(size)},...(signal?{signal}:{})})));},
 async openLoyaltyAccount(org:string,customerId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),customer=assertUuid(customerId,"customerId");const r=parseLoyaltyAccount(required(await client.post<unknown>(organizationPath(o,"loyalty","accounts"),{body:{customerId:customer},idempotencyKey:randomUUID(),...(signal?{signal}:{})})));if(r.customerId!==customer)throw new CommerceContractError("loyaltyAccount");return r;},
 async changeLoyaltyPoints(org:string,account:LoyaltyAccount,kind:"earn"|"redeem",points:number,reason:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),id=assertUuid(account.id,"accountId");if(!Number.isSafeInteger(points)||points<1||points>1_000_000)throw new TypeError("Points are invalid.");const r=parseLoyaltyPointsResult(required(await client.post<unknown>(organizationPath(o,"loyalty","accounts",id,kind),{body:{points,reason:clean(reason,200,"Reason")},idempotencyKey:randomUUID(),...(signal?{signal}:{})})));if(r.account.id!==id)throw new CommerceContractError("loyaltyAccount");return r;},
 });}
export type CommerceExtensions=ReturnType<typeof createCommerceExtensions>;
