import { randomUUID } from "expo-crypto";
import { assertUuid, organizationPath, type ApiClient } from "@salekhpos/packages-api-client";
import { GlobalConfigurationContractError, parseNotification, parseNotificationDeliveryPage, parseNotificationPage, parseNotificationPreferences, parseTaxCalculation, parseTaxProfile, parseTaxProfilePage, parseTaxRate, parseTaxRates, parseLocalizationSettings, parseLocalizationWriteResult, type NotificationDeliveryStatus, type NotificationPreferences, type LocalizationSettings } from "@/api/globalConfigurationContracts";

function required<T>(value:T|undefined):T{if(value===undefined)throw new GlobalConfigurationContractError("response");return value}
function clean(value:string,max:number,label:string){const v=value.trim();if(!v||v.length>max||/[\u0000-\u001f\u007f]/u.test(v))throw new TypeError(`${label} is invalid.`);return v}
function amount(value:number,label:string,min=0,max=1e15){if(!Number.isFinite(value)||value<min||value>max)throw new TypeError(`${label} is invalid.`);return value}
function instant(value:string,label:string){const d=new Date(value);if(!Number.isFinite(d.getTime()))throw new TypeError(`${label} is invalid.`);return d.toISOString()}

export function createGlobalConfiguration(client:ApiClient){return Object.freeze({
 async listNotifications(org:string,unreadOnly=false,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseNotificationPage(required(await client.get<unknown>(organizationPath(o,"notifications"),{query:{pageSize:100,unreadOnly},...(signal?{signal}:{})})));},
 async markNotificationRead(org:string,id:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),notification=assertUuid(id,"notificationId");return parseNotification(required(await client.post<unknown>(organizationPath(o,"notifications",notification,"read"),{body:{},...(signal?{signal}:{})})));},
 async listNotificationDeliveries(org:string,input:{status?:NotificationDeliveryStatus;channel?:"email"|"push";after?:string}={},signal?:AbortSignal){const o=assertUuid(org,"organizationId");const query:Record<string,string|number>={pageSize:25};if(input.status)query.status=input.status;if(input.channel)query.channel=input.channel;if(input.after)query.after=assertUuid(input.after,"deliveryCursor");return parseNotificationDeliveryPage(required(await client.get<unknown>(organizationPath(o,"notifications","deliveries"),{query,...(signal?{signal}:{})})));},
 async readNotificationPreferences(org:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseNotificationPreferences(required(await client.get<unknown>(organizationPath(o,"notifications","preferences"),signal?{signal}:{})));},
 async updateNotificationPreferences(org:string,prefs:Pick<NotificationPreferences,"inAppEnabled"|"emailEnabled"|"pushEnabled">,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseNotificationPreferences(required(await client.put<unknown>(organizationPath(o,"notifications","preferences"),{body:prefs,...(signal?{signal}:{})})));},
 async listTaxProfiles(org:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseTaxProfilePage(required(await client.get<unknown>(organizationPath(o,"tax-profiles"),{query:{pageSize:100},...(signal?{signal}:{})})));},
 async createTaxProfile(org:string,input:{code:string;name:string;countryCode:string;pricesIncludeTax:boolean},signal?:AbortSignal){const o=assertUuid(org,"organizationId");const body={code:clean(input.code,40,"Code").toUpperCase(),name:clean(input.name,120,"Name"),countryCode:clean(input.countryCode,2,"Country").toUpperCase(),pricesIncludeTax:input.pricesIncludeTax};return parseTaxProfile(required(await client.post<unknown>(organizationPath(o,"tax-profiles"),{body,idempotencyKey:randomUUID(),...(signal?{signal}:{})})));},
 async listTaxRates(org:string,profileId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),p=assertUuid(profileId,"profileId");return parseTaxRates(required(await client.get<unknown>(organizationPath(o,"tax-profiles",p,"rates"),signal?{signal}:{})));},
 async createTaxRate(org:string,profileId:string,input:{branchId?:string;categoryCode:string;ratePercent:number;effectiveFrom:string;effectiveUntil?:string},signal?:AbortSignal){const o=assertUuid(org,"organizationId"),p=assertUuid(profileId,"profileId");const body={branchId:input.branchId?assertUuid(input.branchId,"branchId"):null,categoryCode:clean(input.categoryCode,40,"Category").toUpperCase(),ratePercent:amount(input.ratePercent,"Rate",0,100),effectiveFrom:instant(input.effectiveFrom,"Effective from"),effectiveUntil:input.effectiveUntil?instant(input.effectiveUntil,"Effective until"):null};return parseTaxRate(required(await client.post<unknown>(organizationPath(o,"tax-profiles",p,"rates"),{body,idempotencyKey:randomUUID(),...(signal?{signal}:{})})));},
 async calculateTax(org:string,input:{profileId:string;branchId:string;categoryCode:string;amount:number;at:string},signal?:AbortSignal){const o=assertUuid(org,"organizationId");const body={profileId:assertUuid(input.profileId,"profileId"),branchId:assertUuid(input.branchId,"branchId"),categoryCode:clean(input.categoryCode,40,"Category").toUpperCase(),amount:amount(input.amount,"Amount"),at:instant(input.at,"At")};return parseTaxCalculation(required(await client.post<unknown>(organizationPath(o,"tax-profiles","calculate"),{body,...(signal?{signal}:{})})));},
 async readLocalization(org:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseLocalizationSettings(required(await client.get<unknown>(organizationPath(o,"localization"),signal?{signal}:{})));},
 async updateLocalization(org:string,input:Pick<LocalizationSettings,"countryCode"|"defaultLocale"|"defaultCurrency"|"timeZone"|"supportedLocales"|"firstDayOfWeek">&{expectedVersion:number|null},signal?:AbortSignal){const o=assertUuid(org,"organizationId");const body={countryCode:clean(input.countryCode,2,"Country").toUpperCase(),defaultLocale:clean(input.defaultLocale,35,"Default locale"),defaultCurrency:clean(input.defaultCurrency,3,"Currency").toUpperCase(),timeZone:clean(input.timeZone,100,"Timezone"),supportedLocales:input.supportedLocales.map(x=>clean(x,35,"Locale")),firstDayOfWeek:input.firstDayOfWeek,expectedVersion:input.expectedVersion};return parseLocalizationWriteResult(required(await client.put<unknown>(organizationPath(o,"localization"),{body,idempotencyKey:randomUUID(),...(signal?{signal}:{})})));},
 });}
export type GlobalConfiguration=ReturnType<typeof createGlobalConfiguration>;
