import { assertUuid, organizationPath, type ApiClient } from "@salekhpos/packages-api-client";
import { SupportContractError, parseDiagnosticReference, parseSupportTicket, parseSupportTicketDetail, parseSupportTicketPage, type SupportPriority, type SupportStatus } from "@/api/supportContracts";

function required<T>(value:T|undefined):T{if(value===undefined)throw new SupportContractError("response");return value}
function clean(value:string,max:number,label:string,multiline=false){const v=value.trim();if(!v||v.length>max||[...v].some(c=>c<" "&&(!multiline||c!=="\r"&&c!=="\n"&&c!=="\t")))throw new TypeError(label+" is invalid.");return v}
function operation(value:string){return assertUuid(value,"operationId")}
const statuses=new Set<SupportStatus>(["open","in_progress","waiting_for_customer","resolved","closed"]);
export function createSupportService(client:ApiClient){return Object.freeze({
 async list(org:string,status?:SupportStatus|null,after?:string|null,signal?:AbortSignal){const o=assertUuid(org,"organizationId");return parseSupportTicketPage(required(await client.get<unknown>(organizationPath(o,"support","tickets"),{query:{pageSize:50,...(status?{status}:{}),...(after?{after:assertUuid(after,"after")}:{})},...(signal?{signal}:{})})));},
 async get(org:string,ticketId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),id=assertUuid(ticketId,"ticketId");return parseSupportTicketDetail(required(await client.get<unknown>(organizationPath(o,"support","tickets",id),signal?{signal}:{})));},
 async create(org:string,input:{branchId:string|null;subject:string;description:string;priority:SupportPriority},operationId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId");const body={branchId:input.branchId?assertUuid(input.branchId,"branchId"):null,subject:clean(input.subject,200,"Subject"),description:clean(input.description,8000,"Description",true),priority:input.priority};return parseSupportTicket(required(await client.post<unknown>(organizationPath(o,"support","tickets"),{body,idempotencyKey:operation(operationId),...(signal?{signal}:{})})));},
 async transition(org:string,ticketId:string,input:{status:SupportStatus;expectedVersion:number;note:string},operationId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),id=assertUuid(ticketId,"ticketId");if(!statuses.has(input.status)||!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<0)throw new TypeError("Transition is invalid.");const body={...input,note:clean(input.note,2000,"Transition note",true)};return parseSupportTicket(required(await client.post<unknown>(organizationPath(o,"support","tickets",id,"transitions"),{body,idempotencyKey:operation(operationId),...(signal?{signal}:{})})));},
 async addDiagnostic(org:string,ticketId:string,input:{kind:string;reference:string;sha256:string},operationId:string,signal?:AbortSignal){const o=assertUuid(org,"organizationId"),id=assertUuid(ticketId,"ticketId"),sha=input.sha256.trim().toLowerCase();if(!/^[0-9a-f]{64}$/u.test(sha))throw new TypeError("SHA-256 is invalid.");const body={kind:clean(input.kind,64,"Kind"),reference:clean(input.reference,512,"Reference"),sha256:sha};return parseDiagnosticReference(required(await client.post<unknown>(organizationPath(o,"support","tickets",id,"diagnostics"),{body,idempotencyKey:operation(operationId),...(signal?{signal}:{})})));},
 });}
export type SupportService=ReturnType<typeof createSupportService>;
