<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Sync.Application/SalekhPos.Sync.Application.csproj" /><ProjectReference Include="../SalekhPos.Sync.Domain/SalekhPos.Sync.Domain.csproj" /><ProjectReference Include="../SalekhPos.Sync.Contracts/SalekhPos.Sync.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
