<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Desktop.Application/SalekhPos.Desktop.Application.csproj" /><ProjectReference Include="../SalekhPos.Desktop.Domain/SalekhPos.Desktop.Domain.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" /><PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" /></ItemGroup></Project>
