<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Fiscalization.Application/SalekhPos.Fiscalization.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Fiscalization.Domain/SalekhPos.Fiscalization.Domain.csproj" />
    <ProjectReference Include="../SalekhPos.Fiscalization.Contracts/SalekhPos.Fiscalization.Contracts.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
