<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Devices.Application/SalekhPos.Devices.Application.csproj" /><ProjectReference Include="../SalekhPos.Devices.Domain/SalekhPos.Devices.Domain.csproj" /><ProjectReference Include="../SalekhPos.Devices.Contracts/SalekhPos.Devices.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
