import { boundedArray, decimal, exactKeys, integer, isoDate, object, optionalUuid, text, uuid } from "@/lib/boundedJson";
import type { Customer, Employee, OperationalReport, Page, PurchaseLine, PurchaseOrder, Supplier } from "./types";

function optionalText(value: unknown, label: string, max: number): string|null { return value===null ? null : text(value,label,max,1); }
function boolean(value: unknown, label: string): boolean { if(typeof value!=="boolean") throw new Error(`Invalid ${label}`); return value; }
function page<T>(value: unknown, item:(x:unknown)=>T): Page<T> { const x=object(value,"page"); exactKeys(x,["items","nextCursor"]); return {items:boundedArray(x.items,"items",100).map(item),nextCursor:optionalUuid(x.nextCursor,"cursor")}; }
export function parseCustomer(value:unknown):Customer { const x=object(value,"customer"); exactKeys(x,["id","code","displayName","email","phone","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),code:text(x.code,"code",32,1),displayName:text(x.displayName,"name",200,1),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseCustomerPage=(v:unknown)=>page(v,parseCustomer);
export function parseSupplier(value:unknown):Supplier { const x=object(value,"supplier"); exactKeys(x,["id","code","name","taxId","email","phone","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),code:text(x.code,"code",32,1),name:text(x.name,"name",200,1),taxId:optionalText(x.taxId,"tax id",64),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseSupplierPage=(v:unknown)=>page(v,parseSupplier);
export function parseEmployee(value:unknown):Employee { const x=object(value,"employee"); exactKeys(x,["id","branchId","code","displayName","email","phone","jobTitle","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),branchId:uuid(x.branchId,"branch"),code:text(x.code,"code",32,1),displayName:text(x.displayName,"name",200,1),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),jobTitle:text(x.jobTitle,"title",120,1),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseEmployeePage=(v:unknown)=>page(v,parseEmployee);
function parseLine(value:unknown):PurchaseLine { const x=object(value,"line"); exactKeys(x,["productId","quantity","unitCost","lineTotal"]); return {productId:uuid(x.productId,"product"),quantity:decimal(x.quantity,"quantity",{min:0,max:1e9}),unitCost:decimal(x.unitCost,"unit cost",{min:0,max:1e12}),lineTotal:decimal(x.lineTotal,"line total",{min:0,max:1e15})}; }
export function parsePurchaseOrder(value:unknown):PurchaseOrder { const x=object(value,"purchase order"); exactKeys(x,["id","branchId","supplierId","status","currency","reference","total","version","createdAt","updatedAt","lines"]); const status=text(x.status,"status",16,1); if(!["draft","submitted","approved","cancelled"].includes(status)) throw new Error("Invalid status"); return {id:uuid(x.id,"id"),branchId:uuid(x.branchId,"branch"),supplierId:uuid(x.supplierId,"supplier"),status:status as PurchaseOrder["status"],currency:text(x.currency,"currency",3,3),reference:optionalText(x.reference,"reference",120),total:decimal(x.total,"total",{min:0,max:1e15}),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated"),lines:boundedArray(x.lines,"lines",500).map(parseLine)}; }
export const parsePurchaseOrderPage=(v:unknown)=>page(v,parsePurchaseOrder);
export function parseOperationalReport(value:unknown):OperationalReport { const x=object(value,"report"); exactKeys(x,["organizationId","branchId","from","to","currency","salesCount","salesGross","returnCount","returnsTotal","netSales","purchaseOrderCount","purchaseOrderTotal","openShiftCount"]); return {organizationId:uuid(x.organizationId,"organization"),branchId:uuid(x.branchId,"branch"),from:isoDate(x.from,"from"),to:isoDate(x.to,"to"),currency:x.currency===null?null:text(x.currency,"currency",3,3),salesCount:integer(x.salesCount,"sales count",0,1e9),salesGross:decimal(x.salesGross,"sales gross",{min:0,max:1e15}),returnCount:integer(x.returnCount,"return count",0,1e9),returnsTotal:decimal(x.returnsTotal,"returns",{min:0,max:1e15}),netSales:decimal(x.netSales,"net sales",{min:-1e15,max:1e15}),purchaseOrderCount:integer(x.purchaseOrderCount,"purchase count",0,1e9),purchaseOrderTotal:decimal(x.purchaseOrderTotal,"purchase total",{min:0,max:1e15}),openShiftCount:integer(x.openShiftCount,"open shifts",0,1e6)}; }

export function parseStockTransfer(value:unknown):import("./types").StockTransfer { const x=object(value,"stock transfer"); exactKeys(x,["id","sourceBranchId","destinationBranchId","status","reference","version","createdAt","updatedAt","dispatchedAt","receivedAt","lines"]); const status=text(x.status,"status",16,1); if(!["draft","in_transit","received","cancelled"].includes(status)) throw new Error("Invalid transfer status"); const lines=boundedArray(x.lines,"lines",500).map(v=>{const l=object(v,"line");exactKeys(l,["productId","quantity"]);return {productId:uuid(l.productId,"product"),quantity:decimal(l.quantity,"quantity",{min:0.000001,max:1e12})};}); return {id:uuid(x.id,"id"),sourceBranchId:uuid(x.sourceBranchId,"source branch"),destinationBranchId:uuid(x.destinationBranchId,"destination branch"),status:status as import("./types").StockTransfer["status"],reference:optionalText(x.reference,"reference",120),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated"),dispatchedAt:x.dispatchedAt===null?null:isoDate(x.dispatchedAt,"dispatched"),receivedAt:x.receivedAt===null?null:isoDate(x.receivedAt,"received"),lines}; }
export const parseStockTransferPage=(v:unknown)=>page(v,parseStockTransfer);
export function parsePromotion(value:unknown):import("./types").Promotion { const x=object(value,"promotion"); exactKeys(x,["id","code","name","branchId","discountKind","value","currency","minimumSubtotal","startsAt","endsAt","isActive","version","createdAt","updatedAt"]); const kind=text(x.discountKind,"discount kind",16,1); if(kind!=="percentage"&&kind!=="fixed")throw new Error("Invalid promotion kind"); return {id:uuid(x.id,"id"),code:text(x.code,"code",40,1),name:text(x.name,"name",160,1),branchId:optionalUuid(x.branchId,"branch"),discountKind:kind,value:decimal(x.value,"value",{min:0.000001,max:1e12}),currency:x.currency===null?null:text(x.currency,"currency",3,3),minimumSubtotal:decimal(x.minimumSubtotal,"minimum subtotal",{min:0,max:1e15}),startsAt:isoDate(x.startsAt,"starts"),endsAt:x.endsAt===null?null:isoDate(x.endsAt,"ends"),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parsePromotionPage=(v:unknown)=>page(v,parsePromotion);
export function parsePromotionEvaluation(value:unknown):import("./types").PromotionEvaluation { const x=object(value,"promotion evaluation"); exactKeys(x,["subtotal","totalDiscount","payable","currency","applied"]); const applied=boundedArray(x.applied,"applied",100).map(v=>{const a=object(v,"applied promotion");exactKeys(a,["promotionId","code","name","discount"]);return {promotionId:uuid(a.promotionId,"promotion"),code:text(a.code,"code",40,1),name:text(a.name,"name",160,1),discount:decimal(a.discount,"discount",{min:0,max:1e15})};}); return {subtotal:decimal(x.subtotal,"subtotal",{min:0,max:1e15}),totalDiscount:decimal(x.totalDiscount,"discount",{min:0,max:1e15}),payable:decimal(x.payable,"payable",{min:0,max:1e15}),currency:text(x.currency,"currency",3,3),applied}; }
export function parseLoyaltyAccount(value:unknown):import("./types").LoyaltyAccount { const x=object(value,"loyalty account"); exactKeys(x,["id","customerId","tier","pointsBalance","lifetimePoints","version","createdAt","updatedAt"]); const tier=text(x.tier,"tier",16,1); if(!["bronze","silver","gold","platinum"].includes(tier))throw new Error("Invalid loyalty tier"); return {id:uuid(x.id,"id"),customerId:uuid(x.customerId,"customer"),tier:tier as import("./types").LoyaltyAccount["tier"],pointsBalance:integer(x.pointsBalance,"points balance",0,Number.MAX_SAFE_INTEGER),lifetimePoints:integer(x.lifetimePoints,"lifetime points",0,Number.MAX_SAFE_INTEGER),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseLoyaltyAccountPage=(v:unknown)=>page(v,parseLoyaltyAccount);
export function parseLoyaltyPointsResult(value:unknown):import("./types").LoyaltyPointsResult { const x=object(value,"loyalty points result"); exactKeys(x,["account","eventId","kind","points","occurredAt","applied"]); const kind=text(x.kind,"kind",16,1); if(kind!=="earn"&&kind!=="redeem")throw new Error("Invalid loyalty event kind"); return {account:parseLoyaltyAccount(x.account),eventId:uuid(x.eventId,"event"),kind,points:integer(x.points,"points",1,1_000_000),occurredAt:isoDate(x.occurredAt,"occurred"),applied:boolean(x.applied,"applied")}; }
