import { boundedArray, decimal, exactKeys, integer, isoDate, object, optionalUuid, text, uuid } from "@/lib/boundedJson";
import type { Customer, Employee, OperationalReport, Page, PurchaseLine, PurchaseOrder, Supplier } from "./types";

function optionalText(value: unknown, label: string, max: number): string|null { return value===null ? null : text(value,label,max,1); }
function boolean(value: unknown, label: string): boolean { if(typeof value!=="boolean") throw new Error(`Invalid ${label}`); return value; }
function page<T>(value: unknown, item:(x:unknown)=>T): Page<T> { const x=object(value,"page"); exactKeys(x,["items","nextCursor"]); return {items:boundedArray(x.items,"items",100).map(item),nextCursor:optionalUuid(x.nextCursor,"cursor")}; }
export function parseCustomer(value:unknown):Customer { const x=object(value,"customer"); exactKeys(x,["id","code","displayName","email","phone","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),code:text(x.code,"code",32,1),displayName:text(x.displayName,"name",200,1),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseCustomerPage=(v:unknown)=>page(v,parseCustomer);
export function parseSupplier(value:unknown):Supplier { const x=object(value,"supplier"); exactKeys(x,["id","code","name","taxId","email","phone","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),code:text(x.code,"code",32,1),name:text(x.name,"name",200,1),taxId:optionalText(x.taxId,"tax id",64),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseSupplierPage=(v:unknown)=>page(v,parseSupplier);
export function parseEmployee(value:unknown):Employee { const x=object(value,"employee"); exactKeys(x,["id","branchId","code","displayName","email","phone","jobTitle","isActive","version","createdAt","updatedAt"]); return {id:uuid(x.id,"id"),branchId:uuid(x.branchId,"branch"),code:text(x.code,"code",32,1),displayName:text(x.displayName,"name",200,1),email:optionalText(x.email,"email",254),phone:optionalText(x.phone,"phone",32),jobTitle:text(x.jobTitle,"title",120,1),isActive:boolean(x.isActive,"active"),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated")}; }
export const parseEmployeePage=(v:unknown)=>page(v,parseEmployee);
function parseLine(value:unknown):PurchaseLine { const x=object(value,"line"); exactKeys(x,["productId","quantity","unitCost","lineTotal"]); return {productId:uuid(x.productId,"product"),quantity:decimal(x.quantity,"quantity",{min:0,max:1e9}),unitCost:decimal(x.unitCost,"unit cost",{min:0,max:1e12}),lineTotal:decimal(x.lineTotal,"line total",{min:0,max:1e15})}; }
export function parsePurchaseOrder(value:unknown):PurchaseOrder { const x=object(value,"purchase order"); exactKeys(x,["id","branchId","supplierId","status","currency","reference","total","version","createdAt","updatedAt","lines"]); const status=text(x.status,"status",16,1); if(!["draft","submitted","approved","cancelled"].includes(status)) throw new Error("Invalid status"); return {id:uuid(x.id,"id"),branchId:uuid(x.branchId,"branch"),supplierId:uuid(x.supplierId,"supplier"),status:status as PurchaseOrder["status"],currency:text(x.currency,"currency",3,3),reference:optionalText(x.reference,"reference",120),total:decimal(x.total,"total",{min:0,max:1e15}),version:integer(x.version,"version",1,Number.MAX_SAFE_INTEGER),createdAt:isoDate(x.createdAt,"created"),updatedAt:isoDate(x.updatedAt,"updated"),lines:boundedArray(x.lines,"lines",500).map(parseLine)}; }
export const parsePurchaseOrderPage=(v:unknown)=>page(v,parsePurchaseOrder);
export function parseOperationalReport(value:unknown):OperationalReport { const x=object(value,"report"); exactKeys(x,["organizationId","branchId","from","to","currency","salesCount","salesGross","returnCount","returnsTotal","netSales","purchaseOrderCount","purchaseOrderTotal","openShiftCount"]); return {organizationId:uuid(x.organizationId,"organization"),branchId:uuid(x.branchId,"branch"),from:isoDate(x.from,"from"),to:isoDate(x.to,"to"),currency:x.currency===null?null:text(x.currency,"currency",3,3),salesCount:integer(x.salesCount,"sales count",0,1e9),salesGross:decimal(x.salesGross,"sales gross",{min:0,max:1e15}),returnCount:integer(x.returnCount,"return count",0,1e9),returnsTotal:decimal(x.returnsTotal,"returns",{min:0,max:1e15}),netSales:decimal(x.netSales,"net sales",{min:-1e15,max:1e15}),purchaseOrderCount:integer(x.purchaseOrderCount,"purchase count",0,1e9),purchaseOrderTotal:decimal(x.purchaseOrderTotal,"purchase total",{min:0,max:1e15}),openShiftCount:integer(x.openShiftCount,"open shifts",0,1e6)}; }
