version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directories:
      - /backend/src/Bootstrapper/SalekhPos.Api
      - /backend/src/BuildingBlocks/SalekhPos.SharedKernel
      - /backend/src/Modules/Organizations
      - /backend/src/Modules/Access
      - /backend/src/Modules/Identity
      - /backend/tests/SalekhPos.Tests
      - /backend/tests/SalekhPos.IntegrationTests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
