using Npgsql;
using NpgsqlTypes;
using SalekhPos.Devices.Application.Devices;
using SalekhPos.Devices.Contracts.Devices;
using SalekhPos.Devices.Domain.Devices;
namespace SalekhPos.Devices.Infrastructure.Devices;

public sealed class PostgresDeviceRegistry(NpgsqlDataSource? source) : IDeviceRegistry
{
    public async Task<DeviceWriteResult> RegisterAsync(DeviceIdentity identity, RegisterDeviceCommand x, CancellationToken ct)
    {
        _ = new RegisteredDevice(x.DeviceId, x.RegisterId, x.Code, x.Name, x.Platform, x.SyncProtocolVersion);
        Validate(identity, x.OrganizationId, x.BranchId, x.OperationId);
        var ds = source ?? throw new DeviceUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct);
        await Demand(c, t, identity, x.OrganizationId, x.BranchId, "devices.manage", ct);
        var replay = await ByOperation(c, t, x.OrganizationId, x.OperationId, ct);
        if (replay is not null) { if (replay.BranchId != x.BranchId || replay.RegisterId != x.RegisterId || replay.Code != x.Code || replay.Name != x.Name || replay.Platform != x.Platform || replay.SyncProtocolVersion != x.SyncProtocolVersion) throw new DeviceConflictException(); await t.CommitAsync(ct); return new(replay, false); }
        if (!await RegisterExists(c, t, x.OrganizationId, x.BranchId, x.RegisterId, ct)) throw new DeviceConflictException();
        var at = await Time(c, t, ct);
        try { await using var q = new NpgsqlCommand("INSERT INTO devices.registered_devices(organization_id,device_id,operation_id,branch_id,register_id,code,name,platform,status,sync_protocol_version,registered_at,issuer,registered_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'active',$9,$10,$11,$12)", c, t); q.Parameters.AddWithValue(x.OrganizationId); q.Parameters.AddWithValue(x.DeviceId); q.Parameters.AddWithValue(x.OperationId); q.Parameters.AddWithValue(x.BranchId); q.Parameters.AddWithValue(x.RegisterId); q.Parameters.AddWithValue(x.Code); q.Parameters.AddWithValue(x.Name); q.Parameters.AddWithValue(x.Platform); q.Parameters.AddWithValue(x.SyncProtocolVersion); q.Parameters.AddWithValue(at); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); }
        catch (PostgresException e) when (e.SqlState == PostgresErrorCodes.UniqueViolation) { throw new DeviceConflictException(); }
        await t.CommitAsync(ct); return new(new(x.DeviceId, x.BranchId, x.RegisterId, x.Code, x.Name, x.Platform, "active", x.SyncProtocolVersion, at, identity.Subject), true);
    }
    public async Task<DeviceResponse?> ReadAsync(DeviceIdentity identity, Guid org, Guid branch, Guid id, CancellationToken ct)
    { Validate(identity, org, branch, id); var ds = source ?? throw new DeviceUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, "devices.view", ct); DeviceResponse? result; await using (var q = new NpgsqlCommand($"{Select} WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(id); await using var r = await q.ExecuteReaderAsync(ct); result = await r.ReadAsync(ct) ? Read(r) : null; } await t.CommitAsync(ct); return result; }
    public async Task<DevicePage> ListAsync(DeviceIdentity identity, Guid org, Guid branch, int size, Guid? after, CancellationToken ct)
    { if (size is < 1 or > 100 || after == Guid.Empty) throw new ArgumentException("Device query is invalid."); ValidateList(identity, org, branch); var ds = source ?? throw new DeviceUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, "devices.view", ct); var items = new List<DeviceResponse>(); await using (var q = new NpgsqlCommand($"{Select} WHERE organization_id=$1 AND branch_id=$2 AND ($3::uuid IS NULL OR device_id>$3) ORDER BY device_id LIMIT $4", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.Add(new NpgsqlParameter { NpgsqlDbType = NpgsqlDbType.Uuid, Value = (object?)after ?? DBNull.Value }); q.Parameters.AddWithValue(size + 1); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) items.Add(Read(r)); } Guid? next = null; if (items.Count > size) { items.RemoveAt(size); next = items[^1].Id; } await t.CommitAsync(ct); return new(items.AsReadOnly(), next); }
    private const string Select = "SELECT device_id,branch_id,register_id,code,name,platform,status,sync_protocol_version,registered_at,registered_by FROM devices.registered_devices";
    private static DeviceResponse Read(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetGuid(1), r.GetGuid(2), r.GetString(3), r.GetString(4), r.GetString(5), r.GetString(6), r.GetInt32(7), r.GetFieldValue<DateTimeOffset>(8), r.GetString(9));
    private static async Task<DeviceResponse?> ByOperation(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid op, CancellationToken ct) { await using var q = new NpgsqlCommand($"{Select} WHERE organization_id=$1 AND operation_id=$2", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(op); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? Read(r) : null; }
    private static async Task<bool> RegisterExists(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid branch, Guid register, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM stores.registers WHERE organization_id=$1 AND branch_id=$2 AND register_id=$3 AND is_active)", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(register); return await q.ExecuteScalarAsync(ct) is true; }
    private static void Validate(DeviceIdentity i, Guid org, Guid branch, Guid value) { ValidateList(i, org, branch); if (value == Guid.Empty) throw new ArgumentException("Device request is invalid."); }
    private static void ValidateList(DeviceIdentity i, Guid org, Guid branch) { if (org == Guid.Empty || branch == Guid.Empty || string.IsNullOrWhiteSpace(i.Issuer) || string.IsNullOrWhiteSpace(i.Subject)) throw new ArgumentException("Device request is invalid."); }
    private static async Task<DateTimeOffset> Time(NpgsqlConnection c, NpgsqlTransaction t, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT statement_timestamp()", c, t); await using var reader = await q.ExecuteReaderAsync(ct); if (!await reader.ReadAsync(ct)) throw new DeviceUnavailableException(); return reader.GetFieldValue<DateTimeOffset>(0); }
    private static async Task Demand(NpgsqlConnection c, NpgsqlTransaction t, DeviceIdentity i, Guid org, Guid branch, string permission, CancellationToken ct) { await using (var q = new NpgsqlCommand("SELECT set_config('app.organization_id',$1,true),set_config('app.issuer',$2,true),set_config('app.subject',$3,true)", c, t)) { q.Parameters.AddWithValue(org.ToString()); q.Parameters.AddWithValue(i.Issuer); q.Parameters.AddWithValue(i.Subject); await q.ExecuteNonQueryAsync(ct); } await using var d = new NpgsqlCommand("SELECT EXISTS(SELECT FROM access.memberships m JOIN access.permission_grants g ON g.organization_id=m.organization_id AND g.membership_id=m.membership_id JOIN organization.branches b ON b.organization_id=m.organization_id AND b.branch_id=$2 JOIN organization.businesses z ON z.organization_id=b.organization_id AND z.business_id=b.business_id JOIN organization.organizations a ON a.organization_id=b.organization_id WHERE m.organization_id=$1 AND m.issuer=$3 AND m.subject=$4 AND m.is_active AND b.is_active AND z.is_active AND a.is_active AND m.valid_from<=statement_timestamp() AND (m.valid_until IS NULL OR m.valid_until>statement_timestamp()) AND g.permission=$5 AND (g.scope_kind='organization' OR (g.scope_kind='business' AND g.business_id=b.business_id) OR (g.scope_kind='region' AND g.business_id=b.business_id AND g.region_id=b.region_id) OR (g.scope_kind='branch' AND g.business_id=b.business_id AND g.branch_id=b.branch_id)))", c, t); d.Parameters.AddWithValue(org); d.Parameters.AddWithValue(branch); d.Parameters.AddWithValue(i.Issuer); d.Parameters.AddWithValue(i.Subject); d.Parameters.AddWithValue(permission); if (await d.ExecuteScalarAsync(ct) is not true) throw new DeviceDeniedException(); }
}
