<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Integrations.Application/SalekhPos.Integrations.Application.csproj" /><ProjectReference Include="../SalekhPos.Integrations.Domain/SalekhPos.Integrations.Domain.csproj" /><ProjectReference Include="../SalekhPos.Integrations.Contracts/SalekhPos.Integrations.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
