<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Accounting.Application/SalekhPos.Accounting.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Accounting.Contracts/SalekhPos.Accounting.Contracts.csproj" />
    <ProjectReference Include="../SalekhPos.Accounting.Domain/SalekhPos.Accounting.Domain.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>