<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Analytics.Application/SalekhPos.Analytics.Application.csproj" /><ProjectReference Include="../SalekhPos.Analytics.Contracts/SalekhPos.Analytics.Contracts.csproj" /><ProjectReference Include="../SalekhPos.Analytics.Domain/SalekhPos.Analytics.Domain.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
