using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Authentication;
using SalekhPos.Fiscalization.Application.FiscalDocuments;
using SalekhPos.Fiscalization.Contracts.FiscalDocuments;
namespace SalekhPos.Api.Authentication;

public static class WebFiscalizationEndpoints
{
    public static void MapWebFiscalizationEndpoints(this WebApplication app) { var g = app.MapGroup("/bff/api/v1").AllowAnonymous().RequireRateLimiting("business"); g.MapPost("/organizations/{organizationId:guid}/fiscal-documents/branches/{branchId:guid}", Submit); g.MapPost("/organizations/{organizationId:guid}/fiscal-documents/{documentId:guid}/retry", Retry); g.MapGet("/organizations/{organizationId:guid}/fiscal-documents/{documentId:guid}", Read); }
    private static async Task<IResult> Submit(Guid organizationId, Guid branchId, SubmitFiscalDocumentRequest request, HttpContext c, WebAuthenticationState s, IAntiforgery a, IFiscalDocumentService service, CancellationToken ct) { var i = await Identity(c, s); if (i is null) return Unauth(s); if (!await WebAuthentication.ValidateMutation(c, a, s.Settings!) || request.DocumentId == Guid.Empty || request.SaleId == Guid.Empty) return Invalid(); var r = await service.SubmitAsync(i, organizationId, branchId, request, ct); return r.Created ? Results.Created($"/bff/api/v1/organizations/{organizationId:D}/fiscal-documents/{r.Document.DocumentId:D}", r) : Results.Ok(r); }
    private static async Task<IResult> Retry(Guid organizationId, Guid documentId, HttpContext c, WebAuthenticationState s, IAntiforgery a, IFiscalDocumentService service, CancellationToken ct) { var i = await Identity(c, s); if (i is null) return Unauth(s); if (!await WebAuthentication.ValidateMutation(c, a, s.Settings!)) return Invalid(); return Results.Ok(await service.RetryAsync(i, organizationId, documentId, ct)); }
    private static async Task<IResult> Read(Guid organizationId, Guid documentId, HttpContext c, WebAuthenticationState s, IFiscalDocumentService service, CancellationToken ct) { var i = await Identity(c, s); if (i is null) return Unauth(s); var v = await service.ReadAsync(i, organizationId, documentId, ct); return v is null ? Results.NotFound() : Results.Ok(v); }
    private static async Task<FiscalIdentity?> Identity(HttpContext c, WebAuthenticationState s) { if (s.Settings is null) return null; var r = await c.AuthenticateAsync(WebAuthentication.CookieScheme); if (!r.Succeeded || r.Principal is null) return null; var iss = r.Principal.FindAll("iss").ToArray(); var sub = r.Principal.FindAll("sub").ToArray(); if (iss.Length != 1 || sub.Length != 1) return null; try { var i = new FiscalIdentity(iss[0].Value, sub[0].Value); i.Validate(); return i; } catch (ArgumentException) { return null; } }
    private static IResult Unauth(WebAuthenticationState s) => s.Settings is null ? Results.Problem(statusCode: 503, title: "Web authentication is unavailable", extensions: new Dictionary<string, object?> { { "code", "web_authentication_unavailable" } }) : Results.Unauthorized();
    private static IResult Invalid() => Results.Problem(statusCode: 400, title: "The fiscal request is invalid", extensions: new Dictionary<string, object?> { { "code", "invalid_fiscal_request" } });
}
