using Npgsql;
using NpgsqlTypes;
using SalekhPos.Stores.Application.Registers;
using SalekhPos.Stores.Contracts.Registers;
using SalekhPos.Stores.Domain.Registers;
namespace SalekhPos.Stores.Infrastructure.Registers;

public sealed class PostgresRegisterCatalog(NpgsqlDataSource? source) : IRegisterCatalog
{
    public async Task<RegisterWriteResult> CreateAsync(StoreIdentity identity, CreateRegisterCommand x, CancellationToken ct)
    {
        _ = new Register(x.RegisterId, x.BranchId, x.Code, x.Name); Validate(identity, x.OrganizationId, x.BranchId, x.OperationId);
        var ds = source ?? throw new StoreUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct);
        await ContextDemand(c, t, identity, x.OrganizationId, x.BranchId, "stores.manage", ct);
        var replay = await ByOperation(c, t, x.OrganizationId, x.OperationId, ct); if (replay is not null) { if (replay.BranchId != x.BranchId || replay.Code != x.Code || replay.Name != x.Name) throw new StoreConflictException(); await t.CommitAsync(ct); return new(replay, false); }
        var at = await Time(c, t, ct); try { await using var q = new NpgsqlCommand("INSERT INTO stores.registers(organization_id,register_id,operation_id,branch_id,code,name,is_active,created_at,issuer,subject) VALUES($1,$2,$3,$4,$5,$6,true,$7,$8,$9)", c, t); q.Parameters.AddWithValue(x.OrganizationId); q.Parameters.AddWithValue(x.RegisterId); q.Parameters.AddWithValue(x.OperationId); q.Parameters.AddWithValue(x.BranchId); q.Parameters.AddWithValue(x.Code); q.Parameters.AddWithValue(x.Name); q.Parameters.AddWithValue(at); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); } catch (PostgresException e) when (e.SqlState == PostgresErrorCodes.UniqueViolation) { throw new StoreConflictException(); }
        await t.CommitAsync(ct); return new(new(x.RegisterId, x.BranchId, x.Code, x.Name, true, at), true);
    }
    public async Task<RegisterPage> ListAsync(StoreIdentity identity, Guid org, Guid branch, int size, Guid? after, CancellationToken ct)
    {
        Validate(identity, org, branch, Guid.NewGuid()); if (size is < 1 or > 100 || after == Guid.Empty) throw new ArgumentException("Register query is invalid."); var ds = source ?? throw new StoreUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await ContextDemand(c, t, identity, org, branch, "stores.view", ct);
        await using var q = new NpgsqlCommand("SELECT register_id,branch_id,code,name,is_active,created_at FROM stores.registers WHERE organization_id=$1 AND branch_id=$2 AND ($3::uuid IS NULL OR register_id>$3) ORDER BY register_id LIMIT $4", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.Add(new NpgsqlParameter { NpgsqlDbType = NpgsqlDbType.Uuid, Value = (object?)after ?? DBNull.Value }); q.Parameters.AddWithValue(size + 1); var items = new List<RegisterResponse>(); await using (var r = await q.ExecuteReaderAsync(ct)) while (await r.ReadAsync(ct)) items.Add(new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), r.GetString(3), r.GetBoolean(4), r.GetFieldValue<DateTimeOffset>(5))); Guid? next = null; if (items.Count > size) { items.RemoveAt(size); next = items[^1].Id; }
        await t.CommitAsync(ct); return new(items.AsReadOnly(), next);
    }
    private static void Validate(StoreIdentity i, Guid o, Guid b, Guid op) { if (o == Guid.Empty || b == Guid.Empty || op == Guid.Empty || string.IsNullOrWhiteSpace(i.Issuer) || string.IsNullOrWhiteSpace(i.Subject)) throw new ArgumentException("Register request is invalid."); }
    private static async Task ContextDemand(NpgsqlConnection c, NpgsqlTransaction t, StoreIdentity i, Guid o, Guid b, string permission, CancellationToken ct) { await using (var q = new NpgsqlCommand("SELECT set_config('app.organization_id',$1,true),set_config('app.issuer',$2,true),set_config('app.subject',$3,true)", c, t)) { q.Parameters.AddWithValue(o.ToString()); q.Parameters.AddWithValue(i.Issuer); q.Parameters.AddWithValue(i.Subject); await q.ExecuteNonQueryAsync(ct); } await using var d = new NpgsqlCommand("SELECT EXISTS(SELECT FROM access.memberships m JOIN access.permission_grants g ON g.organization_id=m.organization_id AND g.membership_id=m.membership_id JOIN organization.branches b ON b.organization_id=m.organization_id AND b.branch_id=$2 JOIN organization.businesses z ON z.organization_id=b.organization_id AND z.business_id=b.business_id JOIN organization.organizations a ON a.organization_id=b.organization_id WHERE m.organization_id=$1 AND m.issuer=$3 AND m.subject=$4 AND m.is_active AND b.is_active AND z.is_active AND a.is_active AND m.valid_from<=statement_timestamp() AND (m.valid_until IS NULL OR m.valid_until>statement_timestamp()) AND g.permission=$5 AND (g.scope_kind='organization' OR (g.scope_kind='business' AND g.business_id=b.business_id) OR (g.scope_kind='region' AND g.business_id=b.business_id AND g.region_id=b.region_id) OR (g.scope_kind='branch' AND g.business_id=b.business_id AND g.branch_id=b.branch_id)))", c, t); d.Parameters.AddWithValue(o); d.Parameters.AddWithValue(b); d.Parameters.AddWithValue(i.Issuer); d.Parameters.AddWithValue(i.Subject); d.Parameters.AddWithValue(permission); if (await d.ExecuteScalarAsync(ct) is not true) throw new StoreDeniedException(); }
    private static async Task<DateTimeOffset> Time(NpgsqlConnection c, NpgsqlTransaction t, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT statement_timestamp()", c, t); await using var reader = await q.ExecuteReaderAsync(ct); if (!await reader.ReadAsync(ct)) throw new StoreUnavailableException(); return reader.GetFieldValue<DateTimeOffset>(0); }
    private static async Task<RegisterResponse?> ByOperation(NpgsqlConnection c, NpgsqlTransaction t, Guid o, Guid op, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT register_id,branch_id,code,name,is_active,created_at FROM stores.registers WHERE organization_id=$1 AND operation_id=$2", c, t); q.Parameters.AddWithValue(o); q.Parameters.AddWithValue(op); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), r.GetString(3), r.GetBoolean(4), r.GetFieldValue<DateTimeOffset>(5)) : null; }
}
