"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { OperationsScopeSelector } from "@/features/operations/OperationsScopeSelector";
import { useOperationsScope } from "@/features/operations/useOperationsScope";
import { createPromotion, deactivatePromotion, evaluatePromotions, getPromotions } from "@/features/management/api";
import type { Promotion, PromotionEvaluation } from "@/features/management/types";

function localToIso(value:string):string{const date=new Date(value);if(Number.isNaN(date.getTime()))throw new Error("Invalid date");return date.toISOString();}
export function PromotionsWorkspace(){
  const scope=useOperationsScope();const [rows,setRows]=useState<Promotion[]>([]);const [evaluation,setEvaluation]=useState<PromotionEvaluation|null>(null);
  const [code,setCode]=useState("");const [name,setName]=useState("");const [kind,setKind]=useState<"percentage"|"fixed">("percentage");const [value,setValue]=useState("10");const [currency,setCurrency]=useState("GEL");const [minimum,setMinimum]=useState("0");const [starts,setStarts]=useState("");const [ends,setEnds]=useState("");const [subtotal,setSubtotal]=useState("100");
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const ready=Boolean(scope.organizationId&&scope.branchId);
  const reload=useCallback(async()=>{if(!scope.organizationId||!scope.branchId)return;try{const page=await getPromotions(scope.organizationId,scope.branchId);setRows(page.items);setError(null);}catch{setError("Promotions could not be loaded.");}},[scope.organizationId,scope.branchId]);
  useEffect(()=>{if(!ready)return;queueMicrotask(()=>void reload());},[ready,reload]);
  async function submit(event:FormEvent){event.preventDefault();if(!ready)return;setBusy(true);setError(null);try{await createPromotion(scope.organizationId,scope.branchId,{code:code.trim().toUpperCase(),name:name.trim(),branchId:scope.branchId,discountKind:kind,value:Number(value),currency:kind==="fixed"?currency.trim().toUpperCase():undefined,minimumSubtotal:Number(minimum),startsAt:starts?localToIso(starts):new Date().toISOString(),endsAt:ends?localToIso(ends):undefined});setCode("");setName("");await reload();}catch{setError("Promotion could not be created.");}finally{setBusy(false);}}
  async function deactivate(row:Promotion){setBusy(true);setError(null);try{await deactivatePromotion(scope.organizationId,scope.branchId,row);await reload();}catch{setError("Promotion could not be deactivated.");}finally{setBusy(false);}}
  async function evaluate(){if(!ready)return;setBusy(true);setError(null);try{setEvaluation(await evaluatePromotions(scope.organizationId,scope.branchId,Number(subtotal),currency.trim().toUpperCase(),new Date().toISOString()));}catch{setError("Promotion evaluation failed.");}finally{setBusy(false);}}
  return <section className="manager-content"><div className="manager-title"><div><span className="eyebrow">PROMOTIONS</span><h1>Campaigns</h1><p>Create bounded discount campaigns and preview the best eligible discount.</p></div><div className="metric-card"><strong>{rows.filter(x=>x.isActive).length}</strong><span>Active campaigns</span></div></div>
  <OperationsScopeSelector scope={scope}/>{error&&<p className="error-banner">{error}</p>}
  <div className="split-grid"><form className="panel" onSubmit={submit}><h2>New campaign</h2><label>Code<input maxLength={40} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Name<input maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Discount type<select value={kind} onChange={e=>setKind(e.target.value as "percentage"|"fixed")}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Value<input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/></label>{kind==="fixed"&&<label>Currency<input maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label>}<label>Minimum subtotal<input inputMode="decimal" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label>Starts<input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label>Ends<input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)}/></label><button disabled={busy||!ready}>{busy?"Working…":"Create promotion"}</button></form>
  <div className="panel"><h2>Discount preview</h2><label>Subtotal<input inputMode="decimal" value={subtotal} onChange={e=>setSubtotal(e.target.value)}/></label><label>Currency<input maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><button type="button" disabled={busy||!ready} onClick={()=>void evaluate()}>Evaluate now</button>{evaluation&&<div className="metric-grid"><article><strong>{evaluation.totalDiscount.toFixed(2)}</strong><span>Discount {evaluation.currency}</span></article><article><strong>{evaluation.payable.toFixed(2)}</strong><span>Payable {evaluation.currency}</span></article></div>}</div></div>
  <div className="panel"><h2>Campaigns</h2><div className="data-list">{rows.map(row=><article key={row.id}><strong>{row.code} · {row.name}</strong><span>{row.discountKind==="percentage"?`${row.value}%`:`${row.value.toFixed(2)} ${row.currency}`} · minimum {row.minimumSubtotal.toFixed(2)}</span><small>{row.isActive?"Active":"Inactive"} · starts {new Date(row.startsAt).toLocaleString()}</small>{row.isActive&&<div className="inline-actions"><button disabled={busy} onClick={()=>void deactivate(row)}>Deactivate</button></div>}</article>)}</div></div></section>;
}
