"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { OperationsScopeSelector } from "@/features/operations/OperationsScopeSelector";
import { useOperationsScope } from "@/features/operations/useOperationsScope";
import { changeLoyaltyPoints, getCustomers, getLoyaltyAccounts, openLoyaltyAccount } from "@/features/management/api";
import type { Customer, LoyaltyAccount } from "@/features/management/types";

export function LoyaltyWorkspace(){
  const scope=useOperationsScope();const [accounts,setAccounts]=useState<LoyaltyAccount[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);
  const [customerId,setCustomerId]=useState("");const [accountId,setAccountId]=useState("");const [points,setPoints]=useState("100");const [reason,setReason]=useState("Manual loyalty adjustment");
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const ready=Boolean(scope.organizationId);
  const reload=useCallback(async()=>{if(!scope.organizationId)return;try{const [a,c]=await Promise.all([getLoyaltyAccounts(scope.organizationId),getCustomers(scope.organizationId)]);setAccounts(a.items);setCustomers(c.items);setAccountId(current=>a.items.some(x=>x.id===current)?current:(a.items[0]?.id??""));const without=c.items.find(x=>!a.items.some(a=>a.customerId===x.id));setCustomerId(current=>c.items.some(x=>x.id===current)?current:(without?.id??c.items[0]?.id??""));setError(null);}catch{setError("Loyalty data could not be loaded.");}},[scope.organizationId]);
  useEffect(()=>{if(!ready)return;queueMicrotask(()=>void reload());},[ready,reload]);
  const selected=useMemo(()=>accounts.find(x=>x.id===accountId),[accounts,accountId]);
  async function open(event:FormEvent){event.preventDefault();if(!ready||!customerId)return;setBusy(true);setError(null);try{await openLoyaltyAccount(scope.organizationId,customerId);await reload();}catch{setError("Loyalty account could not be opened.");}finally{setBusy(false);}}
  async function change(action:"earn"|"redeem"){if(!ready||!accountId)return;const amount=Number(points);if(!Number.isSafeInteger(amount)||amount<1)return;setBusy(true);setError(null);try{await changeLoyaltyPoints(scope.organizationId,accountId,action,amount,reason.trim());await reload();}catch{setError(`Points could not be ${action==="earn"?"earned":"redeemed"}.`);}finally{setBusy(false);}}
  return <section className="manager-content"><div className="manager-title"><div><span className="eyebrow">LOYALTY</span><h1>Customer loyalty</h1><p>Manage customer point balances with an immutable earn and redeem ledger.</p></div><div className="metric-card"><strong>{accounts.length}</strong><span>Loyalty accounts</span></div></div>
  <OperationsScopeSelector scope={scope}/>{error&&<p className="error-banner">{error}</p>}
  <div className="split-grid"><form className="panel" onSubmit={open}><h2>Open account</h2><label>Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="" disabled>Select customer</option>{customers.map(x=><option key={x.id} value={x.id}>{x.code} · {x.displayName}</option>)}</select></label><button disabled={busy||!ready||!customerId}>Open loyalty account</button></form>
  <div className="panel"><h2>Points transaction</h2><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="" disabled>Select account</option>{accounts.map(x=>{const customer=customers.find(c=>c.id===x.customerId);return <option key={x.id} value={x.id}>{customer?.displayName??x.customerId.slice(0,8)} · {x.pointsBalance} pts</option>})}</select></label><label>Points<input inputMode="numeric" value={points} onChange={e=>setPoints(e.target.value)}/></label><label>Reason<input maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="inline-actions"><button type="button" disabled={busy||!selected} onClick={()=>void change("earn")}>Earn</button><button type="button" disabled={busy||!selected} onClick={()=>void change("redeem")}>Redeem</button></div>{selected&&<p className="muted">{selected.pointsBalance} points · {selected.tier} tier · lifetime {selected.lifetimePoints}</p>}</div></div>
  <div className="panel"><h2>Accounts</h2><div className="data-list">{accounts.map(account=>{const customer=customers.find(x=>x.id===account.customerId);return <article key={account.id}><strong>{customer?.displayName??account.customerId.slice(0,8).toUpperCase()}</strong><span>{account.pointsBalance} points · {account.tier}</span><small>Lifetime {account.lifetimePoints} · version {account.version}</small></article>})}</div></div></section>;
}
