<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../SalekhPos.Authorization.Application/SalekhPos.Authorization.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Authorization.Contracts/SalekhPos.Authorization.Contracts.csproj" />
  </ItemGroup>
</Project>
