<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Inventory.Application/SalekhPos.Inventory.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Inventory.Contracts/SalekhPos.Inventory.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
