<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Localization.Application/SalekhPos.Localization.Application.csproj" /><ProjectReference Include="../SalekhPos.Localization.Contracts/SalekhPos.Localization.Contracts.csproj" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
