<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Stores.Application/SalekhPos.Stores.Application.csproj" /><ProjectReference Include="../SalekhPos.Stores.Domain/SalekhPos.Stores.Domain.csproj" /><ProjectReference Include="../SalekhPos.Stores.Contracts/SalekhPos.Stores.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
