"use client";
import { useCallback, useEffect, useState } from "react";
import { OperationsScopeSelector } from "@/features/operations/OperationsScopeSelector";
import { useOperationsScope } from "@/features/operations/useOperationsScope";
import { calculateTax, createTaxProfile, createTaxRate, getTaxProfiles, getTaxRates } from "./api";
import type { TaxCalculation, TaxProfile, TaxRate } from "./types";

export function TaxationWorkspace(){
 const scope=useOperationsScope();
 const [profiles,setProfiles]=useState<readonly TaxProfile[]>([]),[rates,setRates]=useState<readonly TaxRate[]>([]);
 const [selected,setSelected]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const [code,setCode]=useState("STANDARD"),[name,setName]=useState("Standard tax"),[country,setCountry]=useState("GE"),[inclusive,setInclusive]=useState(true);
 const [category,setCategory]=useState("STANDARD"),[rate,setRate]=useState("18"),[branchSpecific,setBranchSpecific]=useState(true);
 const [amount,setAmount]=useState("100"),[calculation,setCalculation]=useState<TaxCalculation|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{if(!scope.organizationId)return;const page=await getTaxProfiles(scope.organizationId,signal);if(signal?.aborted)return;setProfiles(page.items);setSelected(current=>page.items.some(x=>x.id===current)?current:(page.items[0]?.id??""));setError(null);},[scope.organizationId]);
 useEffect(()=>{if(!scope.organizationId)return;const c=new AbortController();queueMicrotask(()=>{if(!c.signal.aborted)void load(c.signal).catch(()=>setError("Tax profiles could not be loaded."));});return()=>c.abort();},[load,scope.organizationId]);
 useEffect(()=>{if(!scope.organizationId||!selected)return;const c=new AbortController();queueMicrotask(()=>{if(!c.signal.aborted)void getTaxRates(scope.organizationId,selected,c.signal).then(setRates).catch(()=>setError("Tax rates could not be loaded."));});return()=>c.abort();},[scope.organizationId,selected]);
 async function addProfile(){if(!scope.organizationId)return;setBusy(true);setError(null);try{const created=await createTaxProfile(scope.organizationId,{code:code.trim().toUpperCase(),name:name.trim(),countryCode:country.trim().toUpperCase(),pricesIncludeTax:inclusive});await load();setSelected(created.id);}catch{setError("Tax profile could not be created.");}finally{setBusy(false)}}
 async function addRate(){if(!scope.organizationId||!selected)return;const value=Number(rate);if(!Number.isFinite(value))return;setBusy(true);setError(null);try{await createTaxRate(scope.organizationId,selected,{...(branchSpecific&&scope.branchId?{branchId:scope.branchId}:{}),categoryCode:category.trim().toUpperCase(),ratePercent:value,effectiveFrom:new Date().toISOString()});setRates(await getTaxRates(scope.organizationId,selected));}catch{setError("Tax rate could not be created.");}finally{setBusy(false)}}
 async function calculate(){if(!scope.organizationId||!scope.branchId||!selected)return;const value=Number(amount);if(!Number.isFinite(value)||value<0)return;setBusy(true);setError(null);try{setCalculation(await calculateTax(scope.organizationId,{profileId:selected,branchId:scope.branchId,categoryCode:category.trim().toUpperCase(),amount:value,at:new Date().toISOString()}));}catch{setError("Tax calculation failed.");}finally{setBusy(false)}}
 return <section className="manager-content"><div className="manager-title"><div><span className="eyebrow">TAXATION</span><h1>Tax configuration</h1><p>Manage country profiles and effective branch tax rates.</p></div><div className="metric-card"><strong>{profiles.length}</strong><span>Profiles loaded</span></div></div>
 <OperationsScopeSelector scope={scope}/>{error&&<p className="error-banner">{error}</p>}
 <div className="split-grid"><div className="panel"><h2>Profiles</h2><label>Code<input value={code} maxLength={40} onChange={e=>setCode(e.target.value)}/></label><label>Name<input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><label>Country<input value={country} maxLength={2} onChange={e=>setCountry(e.target.value.toUpperCase())}/></label><label><input type="checkbox" checked={inclusive} onChange={e=>setInclusive(e.target.checked)}/> Prices include tax</label><button disabled={busy||!scope.organizationId||!code.trim()||!name.trim()} onClick={()=>void addProfile()}>Create profile</button>
 <label>Active profile<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select profile</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label></div>
 <div className="panel"><h2>Rates and calculator</h2><label>Category<input value={category} maxLength={40} onChange={e=>setCategory(e.target.value)}/></label><label>Rate %<input value={rate} inputMode="decimal" onChange={e=>setRate(e.target.value)}/></label><label><input type="checkbox" checked={branchSpecific} onChange={e=>setBranchSpecific(e.target.checked)}/> Branch-specific rate</label><button disabled={busy||!selected||branchSpecific&&!scope.branchId} onClick={()=>void addRate()}>Add effective rate</button>
 <div className="data-list">{rates.map(r=><article key={r.id}><strong>{r.categoryCode} · {r.ratePercent}%</strong><span>{r.branchId?`Branch ${r.branchId.slice(0,8)}`:"Organization-wide"} · from {new Date(r.effectiveFrom).toLocaleString()}</span></article>)}</div>
 <label>Amount<input value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value)}/></label><button disabled={busy||!selected||!scope.branchId} onClick={()=>void calculate()}>Calculate tax</button>{calculation&&<p><strong>Net {calculation.netAmount.toFixed(2)} · Tax {calculation.taxAmount.toFixed(2)} · Gross {calculation.grossAmount.toFixed(2)}</strong></p>}</div></div></section>;
}
