BEGIN;
DO $$ BEGIN IF current_user='salekhpos_runtime' THEN RAISE EXCEPTION 'Runtime role must not run migrations'; END IF; END $$;
ALTER TABLE devices.registered_devices DROP CONSTRAINT registered_devices_status_check;
ALTER TABLE devices.registered_devices ADD CONSTRAINT registered_devices_status_check CHECK(status IN('pending','active','revoked')), ADD COLUMN revoked_at timestamptz, ADD COLUMN revoked_issuer text, ADD COLUMN revoked_by text, ADD COLUMN revocation_operation_id uuid, ADD COLUMN revocation_reason varchar(256), ADD CONSTRAINT registered_devices_revocation_check CHECK((status<>'revoked' AND revoked_at IS NULL AND revoked_issuer IS NULL AND revoked_by IS NULL AND revocation_operation_id IS NULL AND revocation_reason IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL AND revoked_issuer IS NOT NULL AND revoked_by IS NOT NULL AND revocation_operation_id IS NOT NULL AND char_length(revocation_reason) BETWEEN 1 AND 256));
CREATE UNIQUE INDEX ux_registered_devices_revocation_operation ON devices.registered_devices(organization_id,revocation_operation_id) WHERE revocation_operation_id IS NOT NULL;
CREATE TABLE devices.device_credentials(
 organization_id uuid NOT NULL, device_id uuid NOT NULL, credential_id uuid NOT NULL, created_operation_id uuid NOT NULL, algorithm varchar(32) NOT NULL, public_key_spki bytea NOT NULL, public_key_fingerprint bytea NOT NULL, status varchar(16) NOT NULL, proof_challenge bytea NOT NULL, proof_expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL, created_issuer text NOT NULL, created_by text NOT NULL, activated_at timestamptz, activated_issuer text, activated_by text, activation_operation_id uuid, revoked_at timestamptz, revoked_issuer text, revoked_by text, revocation_operation_id uuid,
 PRIMARY KEY(organization_id,device_id,credential_id), UNIQUE(organization_id,created_operation_id), FOREIGN KEY(organization_id,device_id) REFERENCES devices.registered_devices(organization_id,device_id), CHECK(algorithm='ecdsa-p256-sha256'), CHECK(octet_length(public_key_spki) BETWEEN 64 AND 256), CHECK(octet_length(public_key_fingerprint)=32), CHECK(status IN('pending','active','revoked')), CHECK(octet_length(proof_challenge)=32), CHECK(proof_expires_at>created_at), CHECK((status='pending' AND activated_at IS NULL AND activated_issuer IS NULL AND activated_by IS NULL AND activation_operation_id IS NULL AND revoked_at IS NULL AND revoked_issuer IS NULL AND revoked_by IS NULL AND revocation_operation_id IS NULL) OR (status='active' AND activated_at IS NOT NULL AND activated_issuer IS NOT NULL AND activated_by IS NOT NULL AND activation_operation_id IS NOT NULL AND revoked_at IS NULL AND revoked_issuer IS NULL AND revoked_by IS NULL AND revocation_operation_id IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL AND revoked_issuer IS NOT NULL AND revoked_by IS NOT NULL AND revocation_operation_id IS NOT NULL)));
CREATE UNIQUE INDEX ux_device_credentials_active ON devices.device_credentials(organization_id,device_id) WHERE status='active';
CREATE UNIQUE INDEX ux_device_credentials_live_fingerprint ON devices.device_credentials(organization_id,public_key_fingerprint) WHERE status IN('pending','active');
CREATE UNIQUE INDEX ux_device_credentials_activation_operation ON devices.device_credentials(organization_id,activation_operation_id) WHERE activation_operation_id IS NOT NULL;
CREATE UNIQUE INDEX ux_device_credentials_revocation_operation ON devices.device_credentials(organization_id,revocation_operation_id) WHERE revocation_operation_id IS NOT NULL;
ALTER TABLE devices.device_credentials ENABLE ROW LEVEL SECURITY; ALTER TABLE devices.device_credentials FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON devices.device_credentials USING(organization_id=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK(organization_id=nullif(current_setting('app.organization_id',true),'')::uuid);
GRANT SELECT ON devices.device_credentials TO salekhpos_runtime;
GRANT INSERT(organization_id,device_id,credential_id,created_operation_id,algorithm,public_key_spki,public_key_fingerprint,status,proof_challenge,proof_expires_at,created_at,created_issuer,created_by) ON devices.device_credentials TO salekhpos_runtime;
GRANT UPDATE(status,activated_at,activated_issuer,activated_by,activation_operation_id,revoked_at,revoked_issuer,revoked_by,revocation_operation_id) ON devices.device_credentials TO salekhpos_runtime;
GRANT UPDATE(status,revoked_at,revoked_issuer,revoked_by,revocation_operation_id,revocation_reason) ON devices.registered_devices TO salekhpos_runtime;
COMMIT;
