<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Employees.Application/SalekhPos.Employees.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Employees.Domain/SalekhPos.Employees.Domain.csproj" />
    <ProjectReference Include="../SalekhPos.Employees.Contracts/SalekhPos.Employees.Contracts.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
