<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Notifications.Application/SalekhPos.Notifications.Application.csproj" /><ProjectReference Include="../SalekhPos.Notifications.Domain/SalekhPos.Notifications.Domain.csproj" /><ProjectReference Include="../SalekhPos.Notifications.Contracts/SalekhPos.Notifications.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
