<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.FeatureManagement.Application/SalekhPos.FeatureManagement.Application.csproj" />
    <ProjectReference Include="../SalekhPos.FeatureManagement.Contracts/SalekhPos.FeatureManagement.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
