<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.ShiftManagement.Application/SalekhPos.ShiftManagement.Application.csproj" /><ProjectReference Include="../SalekhPos.ShiftManagement.Domain/SalekhPos.ShiftManagement.Domain.csproj" /><ProjectReference Include="../SalekhPos.ShiftManagement.Contracts/SalekhPos.ShiftManagement.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
