<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Localization.Application/SalekhPos.Localization.Application.csproj" /><ProjectReference Include="../SalekhPos.Localization.Domain/SalekhPos.Localization.Domain.csproj" /><ProjectReference Include="../SalekhPos.Localization.Contracts/SalekhPos.Localization.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
