const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export class AccountingContractError extends Error{constructor(readonly field:string){super(`Invalid accounting field '${field}'.`);this.name="AccountingContractError";}}
export type AccountingSummary=Readonly<{branchId:string;from:string;to:string;currency:string|null;completedSales:number;salesNet:number;salesTax:number;salesGross:number;completedReturns:number;refunds:number;netReceipts:number;cashIn:number;cashOut:number;approvedPurchaseOrders:number;purchaseCommitments:number;closedShifts:number;shiftVariance:number}>;
export type AccountingJournalItem=Readonly<{sourceId:string;kind:"sale"|"return"|"sale_void"|"cash_in"|"cash_out"|"purchase_commitment";occurredAt:string;currency:string;netAmount:number|null;taxAmount:number|null;grossAmount:number;cashEffect:number}>;
export type AccountingJournalPage=Readonly<{items:readonly AccountingJournalItem[];nextCursor:string|null}>;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new AccountingContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:string[],f:string){if(a.some(x=>!(x in v))||Object.keys(v).some(x=>!a.includes(x)))throw new AccountingContractError(f)}
function text(v:unknown,f:string,max:number,min=1){if(typeof v!=="string"||v.length<min||v.length>max||v.trim()!==v||/[\u0000-\u001f\u007f]/u.test(v))throw new AccountingContractError(f);return v}
function id(v:unknown,f:string){const x=text(v,f,36,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new AccountingContractError(f);return x.toLowerCase()}
function integer(v:unknown,f:string){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<0)throw new AccountingContractError(f);return v}
function num(v:unknown,f:string,min=-1e15,max=1e15){if(typeof v!=="number"||!Number.isFinite(v)||v<min||v>max)throw new AccountingContractError(f);return v}
function instant(v:unknown,f:string){const x=text(v,f,64,10);if(!Number.isFinite(Date.parse(x)))throw new AccountingContractError(f);return new Date(x).toISOString()}
function currency(v:unknown){if(v===null)return null;const x=text(v,"currency",3,3);if(!/^[A-Z]{3}$/u.test(x))throw new AccountingContractError("currency");return x}
function requiredCurrency(v:unknown){const x=currency(v);if(x===null)throw new AccountingContractError("currency");return x}
function nullableNum(v:unknown,f:string){return v===null?null:num(v,f)}
export function parseAccountingSummary(v:unknown):AccountingSummary{const x=obj(v,"summary");keys(x,["branchId","from","to","currency","completedSales","salesNet","salesTax","salesGross","completedReturns","refunds","netReceipts","cashIn","cashOut","approvedPurchaseOrders","purchaseCommitments","closedShifts","shiftVariance"],"summary");return {branchId:id(x.branchId,"branchId"),from:instant(x.from,"from"),to:instant(x.to,"to"),currency:currency(x.currency),completedSales:integer(x.completedSales,"completedSales"),salesNet:num(x.salesNet,"salesNet",0),salesTax:num(x.salesTax,"salesTax",0),salesGross:num(x.salesGross,"salesGross",0),completedReturns:integer(x.completedReturns,"completedReturns"),refunds:num(x.refunds,"refunds",0),netReceipts:num(x.netReceipts,"netReceipts"),cashIn:num(x.cashIn,"cashIn",0),cashOut:num(x.cashOut,"cashOut",0),approvedPurchaseOrders:integer(x.approvedPurchaseOrders,"approvedPurchaseOrders"),purchaseCommitments:num(x.purchaseCommitments,"purchaseCommitments",0),closedShifts:integer(x.closedShifts,"closedShifts"),shiftVariance:num(x.shiftVariance,"shiftVariance")}}
const kinds=new Set(["sale","return","sale_void","cash_in","cash_out","purchase_commitment"]);
function journalItem(v:unknown):AccountingJournalItem{const x=obj(v,"journalItem");keys(x,["sourceId","kind","occurredAt","currency","netAmount","taxAmount","grossAmount","cashEffect"],"journalItem");const kind=text(x.kind,"kind",32);if(!kinds.has(kind))throw new AccountingContractError("kind");return {sourceId:id(x.sourceId,"sourceId"),kind:kind as AccountingJournalItem["kind"],occurredAt:instant(x.occurredAt,"occurredAt"),currency:requiredCurrency(x.currency),netAmount:nullableNum(x.netAmount,"netAmount"),taxAmount:nullableNum(x.taxAmount,"taxAmount"),grossAmount:num(x.grossAmount,"grossAmount",0),cashEffect:num(x.cashEffect,"cashEffect")}}
export function parseAccountingJournalPage(v:unknown):AccountingJournalPage{const x=obj(v,"journal");keys(x,["items","nextCursor"],"journal");if(!Array.isArray(x.items)||x.items.length>100)throw new AccountingContractError("items");const next=x.nextCursor===null?null:text(x.nextCursor,"nextCursor",256);return {items:x.items.map(journalItem),nextCursor:next}}
