const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export class AnalyticsContractError extends Error{constructor(readonly field:string){super(`Invalid analytics field '${field}'.`);this.name="AnalyticsContractError";}}
export type AnalyticsOverview=Readonly<{branchId:string;from:string;to:string;currency:string|null;completedSales:number;grossSales:number;completedReturns:number;refunds:number;netRevenue:number;averageTicket:number;distinctProductsSold:number;positiveStockProducts:number;zeroStockProducts:number;negativeStockProducts:number}>;
export type SalesTrendPoint=Readonly<{bucketStart:string;currency:string|null;completedSales:number;grossSales:number;refunds:number;netRevenue:number}>;
export type SalesTrend=Readonly<{branchId:string;from:string;to:string;points:readonly SalesTrendPoint[]}>;
export type StoreComparisonRow=Readonly<{branchId:string;currency:string|null;completedSales:number;grossSales:number;refunds:number;netRevenue:number;averageTicket:number}>;
export type StoreComparison=Readonly<{from:string;to:string;items:readonly StoreComparisonRow[]}>;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new AnalyticsContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:string[],f:string){if(a.some(x=>!(x in v))||Object.keys(v).some(x=>!a.includes(x)))throw new AnalyticsContractError(f)}
function text(v:unknown,f:string,max:number,min=1){if(typeof v!=="string"||v.length<min||v.length>max||v.trim()!==v||/[\u0000-\u001f\u007f]/u.test(v))throw new AnalyticsContractError(f);return v}
function id(v:unknown,f:string){const x=text(v,f,36,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new AnalyticsContractError(f);return x.toLowerCase()}
function integer(v:unknown,f:string){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<0)throw new AnalyticsContractError(f);return v}
function num(v:unknown,f:string,min=-1e15,max=1e15){if(typeof v!=="number"||!Number.isFinite(v)||v<min||v>max)throw new AnalyticsContractError(f);return v}
function instant(v:unknown,f:string){const x=text(v,f,64,10);if(!Number.isFinite(Date.parse(x)))throw new AnalyticsContractError(f);return new Date(x).toISOString()}
function currency(v:unknown){if(v===null)return null;const x=text(v,"currency",3,3);if(!/^[A-Z]{3}$/u.test(x))throw new AnalyticsContractError("currency");return x}
export function parseAnalyticsOverview(v:unknown):AnalyticsOverview{const x=obj(v,"overview");keys(x,["branchId","from","to","currency","completedSales","grossSales","completedReturns","refunds","netRevenue","averageTicket","distinctProductsSold","positiveStockProducts","zeroStockProducts","negativeStockProducts"],"overview");return {branchId:id(x.branchId,"branchId"),from:instant(x.from,"from"),to:instant(x.to,"to"),currency:currency(x.currency),completedSales:integer(x.completedSales,"completedSales"),grossSales:num(x.grossSales,"grossSales",0),completedReturns:integer(x.completedReturns,"completedReturns"),refunds:num(x.refunds,"refunds",0),netRevenue:num(x.netRevenue,"netRevenue"),averageTicket:num(x.averageTicket,"averageTicket",0),distinctProductsSold:integer(x.distinctProductsSold,"distinctProductsSold"),positiveStockProducts:integer(x.positiveStockProducts,"positiveStockProducts"),zeroStockProducts:integer(x.zeroStockProducts,"zeroStockProducts"),negativeStockProducts:integer(x.negativeStockProducts,"negativeStockProducts")}}
function parseTrendPoint(v:unknown):SalesTrendPoint{const x=obj(v,"trendPoint");keys(x,["bucketStart","currency","completedSales","grossSales","refunds","netRevenue"],"trendPoint");return {bucketStart:instant(x.bucketStart,"bucketStart"),currency:currency(x.currency),completedSales:integer(x.completedSales,"completedSales"),grossSales:num(x.grossSales,"grossSales",0),refunds:num(x.refunds,"refunds",0),netRevenue:num(x.netRevenue,"netRevenue")}}
export function parseSalesTrend(v:unknown):SalesTrend{const x=obj(v,"salesTrend");keys(x,["branchId","from","to","points"],"salesTrend");if(!Array.isArray(x.points)||x.points.length>366)throw new AnalyticsContractError("points");return {branchId:id(x.branchId,"branchId"),from:instant(x.from,"from"),to:instant(x.to,"to"),points:x.points.map(parseTrendPoint)}}
function parseStore(v:unknown):StoreComparisonRow{const x=obj(v,"store");keys(x,["branchId","currency","completedSales","grossSales","refunds","netRevenue","averageTicket"],"store");return {branchId:id(x.branchId,"branchId"),currency:currency(x.currency),completedSales:integer(x.completedSales,"completedSales"),grossSales:num(x.grossSales,"grossSales",0),refunds:num(x.refunds,"refunds",0),netRevenue:num(x.netRevenue,"netRevenue"),averageTicket:num(x.averageTicket,"averageTicket",0)}}
export function parseStoreComparison(v:unknown):StoreComparison{const x=obj(v,"storeComparison");keys(x,["from","to","items"],"storeComparison");if(!Array.isArray(x.items)||x.items.length>500)throw new AnalyticsContractError("items");return {from:instant(x.from,"from"),to:instant(x.to,"to"),items:x.items.map(parseStore)}}
