export class AuditContractError extends Error{constructor(readonly field:string){super(`Invalid audit field '${field}'.`);this.name="AuditContractError";}}
export type AuditEvent=Readonly<{id:string;sequence:number;actorSubject:string;action:string;targetType:string;targetId:string|null;branchId:string|null;deviceId:string|null;sourceIp:string|null;outcome:string;reason:string|null;correlationId:string;requestId:string;occurredAt:string;previousHash:string;eventHash:string}>;
export type AuditPage=Readonly<{items:readonly AuditEvent[];nextSequence:number|null}>;
export type AuditIntegrity=Readonly<{isValid:boolean;verifiedEvents:number;firstSequence:number|null;lastSequence:number|null;lastHash:string|null}>;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new AuditContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:string[],f:string){if(Object.keys(v).some(k=>!a.includes(k))||a.some(k=>!(k in v)))throw new AuditContractError(f)}
function text(v:unknown,f:string,max:number):string{if(typeof v!=="string"||v.length<1||v.length>max||v.trim()!==v)throw new AuditContractError(f);return v}
function id(v:unknown,f:string):string{const x=text(v,f,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new AuditContractError(f);return x.toLowerCase()}
function maybeId(v:unknown,f:string):string|null{return v===null?null:id(v,f)}
function maybeText(v:unknown,f:string,max:number):string|null{return v===null?null:text(v,f,max)}
function seq(v:unknown,f:string,allowZero=false):number{if(typeof v!=="number"||!Number.isSafeInteger(v)||v<(allowZero?0:1))throw new AuditContractError(f);return v}
export function parseAuditEvent(v:unknown):AuditEvent{const x=obj(v,"event");keys(x,["id","sequence","actorSubject","action","targetType","targetId","branchId","deviceId","sourceIp","outcome","reason","correlationId","requestId","occurredAt","previousHash","eventHash"],"event");return{id:id(x.id,"id"),sequence:seq(x.sequence,"sequence"),actorSubject:text(x.actorSubject,"actor",256),action:text(x.action,"action",120),targetType:text(x.targetType,"target",80),targetId:maybeId(x.targetId,"targetId"),branchId:maybeId(x.branchId,"branchId"),deviceId:maybeId(x.deviceId,"deviceId"),sourceIp:maybeText(x.sourceIp,"sourceIp",80),outcome:text(x.outcome,"outcome",32),reason:maybeText(x.reason,"reason",500),correlationId:text(x.correlationId,"correlation",128),requestId:text(x.requestId,"request",128),occurredAt:text(x.occurredAt,"occurredAt",64),previousHash:text(x.previousHash,"previousHash",64),eventHash:text(x.eventHash,"eventHash",64)}}
export function parseAuditPage(v:unknown):AuditPage{const x=obj(v,"page");keys(x,["items","nextSequence"],"page");if(!Array.isArray(x.items)||x.items.length>100)throw new AuditContractError("items");return{items:x.items.map(parseAuditEvent),nextSequence:x.nextSequence===null?null:seq(x.nextSequence,"nextSequence")}}
export function parseAuditIntegrity(v:unknown):AuditIntegrity{const x=obj(v,"integrity");keys(x,["isValid","verifiedEvents","firstSequence","lastSequence","lastHash"],"integrity");if(typeof x.isValid!=="boolean")throw new AuditContractError("isValid");return{isValid:x.isValid,verifiedEvents:seq(x.verifiedEvents,"verifiedEvents",true),firstSequence:x.firstSequence===null?null:seq(x.firstSequence,"firstSequence"),lastSequence:x.lastSequence===null?null:seq(x.lastSequence,"lastSequence"),lastHash:maybeText(x.lastHash,"lastHash",64)}}
