const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export class CommerceContractError extends Error{constructor(readonly field:string){super(`Invalid commerce field '${field}'.`);this.name="CommerceContractError";}}
export type StockTransfer=Readonly<{id:string;sourceBranchId:string;destinationBranchId:string;status:"draft"|"in_transit"|"received"|"cancelled";reference:string|null;version:number;createdAt:string;updatedAt:string;dispatchedAt:string|null;receivedAt:string|null;lines:readonly {productId:string;quantity:number}[]}>;
export type Promotion=Readonly<{id:string;code:string;name:string;branchId:string|null;discountKind:"percentage"|"fixed";value:number;currency:string|null;minimumSubtotal:number;startsAt:string;endsAt:string|null;isActive:boolean;version:number;createdAt:string;updatedAt:string}>;
export type PromotionEvaluation=Readonly<{subtotal:number;totalDiscount:number;payable:number;currency:string;applied:readonly {promotionId:string;code:string;name:string;discount:number}[]}>;
export type LoyaltyAccount=Readonly<{id:string;customerId:string;tier:"bronze"|"silver"|"gold"|"platinum";pointsBalance:number;lifetimePoints:number;version:number;createdAt:string;updatedAt:string}>;
export type LoyaltyPointsResult=Readonly<{account:LoyaltyAccount;eventId:string;kind:"earn"|"redeem";points:number;occurredAt:string;applied:boolean}>;
export type UuidPage<T>=Readonly<{items:readonly T[];nextCursor:string|null}>;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new CommerceContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:string[],f:string){const k=Object.keys(v);if(a.some(x=>!(x in v))||k.some(x=>!a.includes(x)))throw new CommerceContractError(f)}
function text(v:unknown,f:string,max:number,min=1){if(typeof v!=="string"||v.length<min||v.length>max||v.trim()!==v||/[\u0000-\u001f\u007f]/u.test(v))throw new CommerceContractError(f);return v}
function id(v:unknown,f:string){const x=text(v,f,36,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new CommerceContractError(f);return x.toLowerCase()}
function number(v:unknown,f:string,min=0){if(typeof v!=="number"||!Number.isFinite(v)||v<min||Math.abs(v)>1e15)throw new CommerceContractError(f);return v}
function integer(v:unknown,f:string,min=0){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<min)throw new CommerceContractError(f);return v}
function instant(v:unknown,f:string){const x=text(v,f,64,10);if(!Number.isFinite(Date.parse(x)))throw new CommerceContractError(f);return new Date(x).toISOString()}
function optionalInstant(v:unknown,f:string){return v===null?null:instant(v,f)}
function optionalText(v:unknown,f:string,max:number){return v===null?null:text(v,f,max)}
function bool(v:unknown,f:string){if(typeof v!=="boolean")throw new CommerceContractError(f);return v}
function page<T>(v:unknown,p:(x:unknown)=>T):UuidPage<T>{const x=obj(v,"page");keys(x,["items","nextCursor"],"page");if(!Array.isArray(x.items)||x.items.length>100)throw new CommerceContractError("items");return {items:x.items.map(p),nextCursor:x.nextCursor===null?null:id(x.nextCursor,"nextCursor")}}
export function parseStockTransfer(v:unknown):StockTransfer{const x=obj(v,"transfer");keys(x,["id","sourceBranchId","destinationBranchId","status","reference","version","createdAt","updatedAt","dispatchedAt","receivedAt","lines"],"transfer");const status=text(x.status,"status",16);if(!["draft","in_transit","received","cancelled"].includes(status)||!Array.isArray(x.lines)||x.lines.length>500)throw new CommerceContractError("transfer");return {id:id(x.id,"id"),sourceBranchId:id(x.sourceBranchId,"sourceBranchId"),destinationBranchId:id(x.destinationBranchId,"destinationBranchId"),status:status as StockTransfer["status"],reference:optionalText(x.reference,"reference",120),version:integer(x.version,"version",1),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt"),dispatchedAt:optionalInstant(x.dispatchedAt,"dispatchedAt"),receivedAt:optionalInstant(x.receivedAt,"receivedAt"),lines:x.lines.map((raw)=>{const l=obj(raw,"line");keys(l,["productId","quantity"],"line");return {productId:id(l.productId,"productId"),quantity:number(l.quantity,"quantity",Number.EPSILON)}})}}
export const parseStockTransferPage=(v:unknown)=>page(v,parseStockTransfer);
export function parsePromotion(v:unknown):Promotion{const x=obj(v,"promotion");keys(x,["id","code","name","branchId","discountKind","value","currency","minimumSubtotal","startsAt","endsAt","isActive","version","createdAt","updatedAt"],"promotion");const kind=text(x.discountKind,"discountKind",16);if(kind!=="percentage"&&kind!=="fixed")throw new CommerceContractError("discountKind");const currency=x.currency===null?null:text(x.currency,"currency",3,3);if(currency!==null&&!/^[A-Z]{3}$/u.test(currency))throw new CommerceContractError("currency");return {id:id(x.id,"id"),code:text(x.code,"code",40),name:text(x.name,"name",160),branchId:x.branchId===null?null:id(x.branchId,"branchId"),discountKind:kind,value:number(x.value,"value",Number.EPSILON),currency,minimumSubtotal:number(x.minimumSubtotal,"minimumSubtotal"),startsAt:instant(x.startsAt,"startsAt"),endsAt:optionalInstant(x.endsAt,"endsAt"),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version",1),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parsePromotionPage=(v:unknown)=>page(v,parsePromotion);
export function parsePromotionEvaluation(v:unknown):PromotionEvaluation{const x=obj(v,"evaluation");keys(x,["subtotal","totalDiscount","payable","currency","applied"],"evaluation");const currency=text(x.currency,"currency",3,3);if(!/^[A-Z]{3}$/u.test(currency)||!Array.isArray(x.applied)||x.applied.length>100)throw new CommerceContractError("evaluation");return {subtotal:number(x.subtotal,"subtotal"),totalDiscount:number(x.totalDiscount,"totalDiscount"),payable:number(x.payable,"payable"),currency,applied:x.applied.map(raw=>{const a=obj(raw,"applied");keys(a,["promotionId","code","name","discount"],"applied");return {promotionId:id(a.promotionId,"promotionId"),code:text(a.code,"code",40),name:text(a.name,"name",160),discount:number(a.discount,"discount")}})}}
export function parseLoyaltyAccount(v:unknown):LoyaltyAccount{const x=obj(v,"loyaltyAccount");keys(x,["id","customerId","tier","pointsBalance","lifetimePoints","version","createdAt","updatedAt"],"loyaltyAccount");const tier=text(x.tier,"tier",16);if(!["bronze","silver","gold","platinum"].includes(tier))throw new CommerceContractError("tier");return {id:id(x.id,"id"),customerId:id(x.customerId,"customerId"),tier:tier as LoyaltyAccount["tier"],pointsBalance:integer(x.pointsBalance,"pointsBalance"),lifetimePoints:integer(x.lifetimePoints,"lifetimePoints"),version:integer(x.version,"version",1),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parseLoyaltyAccountPage=(v:unknown)=>page(v,parseLoyaltyAccount);
export function parseLoyaltyPointsResult(v:unknown):LoyaltyPointsResult{const x=obj(v,"loyaltyPoints");keys(x,["account","eventId","kind","points","occurredAt","applied"],"loyaltyPoints");const kind=text(x.kind,"kind",16);if(kind!=="earn"&&kind!=="redeem")throw new CommerceContractError("kind");return {account:parseLoyaltyAccount(x.account),eventId:id(x.eventId,"eventId"),kind,points:integer(x.points,"points",1),occurredAt:instant(x.occurredAt,"occurredAt"),applied:bool(x.applied,"applied")}}
