const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export class GlobalConfigurationContractError extends Error{constructor(readonly field:string){super(`Invalid configuration field '${field}'.`);this.name="GlobalConfigurationContractError";}}
export type NotificationItem=Readonly<{id:string;branchId:string|null;recipientSubject:string;title:string;body:string;severity:"info"|"warning"|"critical";isRead:boolean;createdAt:string;readAt:string|null}>;
export type NotificationPreferences=Readonly<{inAppEnabled:boolean;emailEnabled:boolean;pushEnabled:boolean;updatedAt:string}>;
export type TaxProfile=Readonly<{id:string;code:string;name:string;countryCode:string;pricesIncludeTax:boolean;isActive:boolean;version:number;createdAt:string;updatedAt:string}>;
export type TaxRate=Readonly<{id:string;profileId:string;branchId:string|null;categoryCode:string;ratePercent:number;effectiveFrom:string;effectiveUntil:string|null;isActive:boolean;version:number}>;
export type TaxCalculation=Readonly<{profileId:string;rateId:string|null;categoryCode:string;ratePercent:number;netAmount:number;taxAmount:number;grossAmount:number;pricesIncludeTax:boolean}>;
export type UuidPage<T>=Readonly<{items:readonly T[];nextCursor:string|null}>;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new GlobalConfigurationContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,a:string[],f:string){if(a.some(x=>!(x in v))||Object.keys(v).some(x=>!a.includes(x)))throw new GlobalConfigurationContractError(f)}
function text(v:unknown,f:string,max:number,min=1){if(typeof v!=="string"||v.length<min||v.length>max||v.trim()!==v||/[\u0000-\u001f\u007f]/u.test(v))throw new GlobalConfigurationContractError(f);return v}
function id(v:unknown,f:string){const x=text(v,f,36,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new GlobalConfigurationContractError(f);return x.toLowerCase()}
function bool(v:unknown,f:string){if(typeof v!=="boolean")throw new GlobalConfigurationContractError(f);return v}
function num(v:unknown,f:string,min=0,max=1e15){if(typeof v!=="number"||!Number.isFinite(v)||v<min||v>max)throw new GlobalConfigurationContractError(f);return v}
function integer(v:unknown,f:string,min=1){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<min)throw new GlobalConfigurationContractError(f);return v}
function instant(v:unknown,f:string){const x=text(v,f,64,10);if(!Number.isFinite(Date.parse(x)))throw new GlobalConfigurationContractError(f);return new Date(x).toISOString()}
function optionalId(v:unknown,f:string){return v===null?null:id(v,f)}
function optionalInstant(v:unknown,f:string){return v===null?null:instant(v,f)}
function page<T>(v:unknown,p:(x:unknown)=>T):UuidPage<T>{const x=obj(v,"page");keys(x,["items","nextCursor"],"page");if(!Array.isArray(x.items)||x.items.length>100)throw new GlobalConfigurationContractError("items");return {items:x.items.map(p),nextCursor:x.nextCursor===null?null:id(x.nextCursor,"nextCursor")}}
export function parseNotification(v:unknown):NotificationItem{const x=obj(v,"notification");keys(x,["id","branchId","recipientSubject","title","body","severity","isRead","createdAt","readAt"],"notification");const severity=text(x.severity,"severity",16);if(!["info","warning","critical"].includes(severity))throw new GlobalConfigurationContractError("severity");return {id:id(x.id,"id"),branchId:optionalId(x.branchId,"branchId"),recipientSubject:text(x.recipientSubject,"recipientSubject",256),title:text(x.title,"title",160),body:text(x.body,"body",2000),severity:severity as NotificationItem["severity"],isRead:bool(x.isRead,"isRead"),createdAt:instant(x.createdAt,"createdAt"),readAt:optionalInstant(x.readAt,"readAt")}}
export const parseNotificationPage=(v:unknown)=>page(v,parseNotification);
export function parseNotificationPreferences(v:unknown):NotificationPreferences{const x=obj(v,"notificationPreferences");keys(x,["inAppEnabled","emailEnabled","pushEnabled","updatedAt"],"notificationPreferences");return {inAppEnabled:bool(x.inAppEnabled,"inAppEnabled"),emailEnabled:bool(x.emailEnabled,"emailEnabled"),pushEnabled:bool(x.pushEnabled,"pushEnabled"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export function parseTaxProfile(v:unknown):TaxProfile{const x=obj(v,"taxProfile");keys(x,["id","code","name","countryCode","pricesIncludeTax","isActive","version","createdAt","updatedAt"],"taxProfile");return {id:id(x.id,"id"),code:text(x.code,"code",40),name:text(x.name,"name",120),countryCode:text(x.countryCode,"countryCode",2,2),pricesIncludeTax:bool(x.pricesIncludeTax,"pricesIncludeTax"),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version"),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parseTaxProfilePage=(v:unknown)=>page(v,parseTaxProfile);
export function parseTaxRate(v:unknown):TaxRate{const x=obj(v,"taxRate");keys(x,["id","profileId","branchId","categoryCode","ratePercent","effectiveFrom","effectiveUntil","isActive","version"],"taxRate");return {id:id(x.id,"id"),profileId:id(x.profileId,"profileId"),branchId:optionalId(x.branchId,"branchId"),categoryCode:text(x.categoryCode,"categoryCode",40),ratePercent:num(x.ratePercent,"ratePercent",0,100),effectiveFrom:instant(x.effectiveFrom,"effectiveFrom"),effectiveUntil:optionalInstant(x.effectiveUntil,"effectiveUntil"),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version")}}
export function parseTaxRates(v:unknown):readonly TaxRate[]{if(!Array.isArray(v)||v.length>500)throw new GlobalConfigurationContractError("taxRates");return v.map(parseTaxRate)}
export function parseTaxCalculation(v:unknown):TaxCalculation{const x=obj(v,"taxCalculation");keys(x,["profileId","rateId","categoryCode","ratePercent","netAmount","taxAmount","grossAmount","pricesIncludeTax"],"taxCalculation");return {profileId:id(x.profileId,"profileId"),rateId:optionalId(x.rateId,"rateId"),categoryCode:text(x.categoryCode,"categoryCode",40),ratePercent:num(x.ratePercent,"ratePercent",0,100),netAmount:num(x.netAmount,"netAmount"),taxAmount:num(x.taxAmount,"taxAmount"),grossAmount:num(x.grossAmount,"grossAmount"),pricesIncludeTax:bool(x.pricesIncludeTax,"pricesIncludeTax")}}
export type LocalizationSettings=Readonly<{countryCode:string;defaultLocale:string;defaultCurrency:string;timeZone:string;supportedLocales:readonly string[];firstDayOfWeek:number;version:number;updatedAt:string}>;
export type LocalizationWriteResult=Readonly<{settings:LocalizationSettings;applied:boolean}>;
export function parseLocalizationSettings(v:unknown):LocalizationSettings{const x=obj(v,"localizationSettings");keys(x,["countryCode","defaultLocale","defaultCurrency","timeZone","supportedLocales","firstDayOfWeek","version","updatedAt"],"localizationSettings");if(!Array.isArray(x.supportedLocales)||x.supportedLocales.length<1||x.supportedLocales.length>20)throw new GlobalConfigurationContractError("supportedLocales");return {countryCode:text(x.countryCode,"countryCode",2,2),defaultLocale:text(x.defaultLocale,"defaultLocale",35,2),defaultCurrency:text(x.defaultCurrency,"defaultCurrency",3,3),timeZone:text(x.timeZone,"timeZone",100),supportedLocales:x.supportedLocales.map((y,i)=>text(y,`supportedLocale${i}`,35,2)),firstDayOfWeek:integer(x.firstDayOfWeek,"firstDayOfWeek"),version:integer(x.version,"version"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export function parseLocalizationWriteResult(v:unknown):LocalizationWriteResult{const x=obj(v,"localizationWrite");keys(x,["settings","applied"],"localizationWrite");return {settings:parseLocalizationSettings(x.settings),applied:bool(x.applied,"applied")}}
