const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export class ManagementContractError extends Error{constructor(readonly field:string){super(`Invalid management field '${field}'.`);this.name="ManagementContractError";}}
export type CustomerSummary=Readonly<{id:string;code:string;displayName:string;email:string|null;phone:string|null;isActive:boolean;version:number;createdAt:string;updatedAt:string}>;
export type SupplierSummary=Readonly<{id:string;code:string;name:string;taxId:string|null;email:string|null;phone:string|null;isActive:boolean;version:number;createdAt:string;updatedAt:string}>;
export type EmployeeSummary=Readonly<{id:string;branchId:string;code:string;displayName:string;email:string|null;phone:string|null;jobTitle:string;isActive:boolean;version:number;createdAt:string;updatedAt:string}>;
export type PurchaseOrderSummary=Readonly<{id:string;branchId:string;supplierId:string;status:"draft"|"submitted"|"approved"|"cancelled";currency:string;reference:string|null;total:number;version:number;createdAt:string;updatedAt:string;lines:readonly PurchaseOrderLineSummary[]}>;
export type PurchaseOrderLineSummary=Readonly<{productId:string;quantity:number;unitCost:number;lineTotal:number}>;
export type OperationalReportSummary=Readonly<{organizationId:string;branchId:string;from:string;to:string;currency:string|null;salesCount:number;salesGross:number;returnCount:number;returnsTotal:number;netSales:number;purchaseOrderCount:number;purchaseOrderTotal:number;openShiftCount:number}>;
export type UuidPage<T>=Readonly<{items:readonly T[];nextCursor:string|null}>;
function obj(v:unknown,f:string):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new ManagementContractError(f);return v as Record<string,unknown>}
function keys(v:Record<string,unknown>,required:string[],f:string){const k=Object.keys(v);if(required.some(x=>!(x in v))||k.some(x=>!required.includes(x)))throw new ManagementContractError(f)}
function txt(v:unknown,f:string,max:number,min=1):string{if(typeof v!=="string"||v.length<min||v.length>max||v.trim()!==v||/[\u0000-\u001f\u007f\uD800-\uDFFF]/u.test(v))throw new ManagementContractError(f);return v}
function id(v:unknown,f:string):string{const x=txt(v,f,36,36);if(!UUID.test(x)||x==="00000000-0000-0000-0000-000000000000")throw new ManagementContractError(f);return x.toLowerCase()}
function maybe(v:unknown,f:string,max:number):string|null{return v===null?null:txt(v,f,max)}
function bool(v:unknown,f:string):boolean{if(typeof v!=="boolean")throw new ManagementContractError(f);return v}
function integer(v:unknown,f:string):number{if(typeof v!=="number"||!Number.isSafeInteger(v)||v<0)throw new ManagementContractError(f);return v}
function money(v:unknown,f:string):number{if(typeof v!=="number"||!Number.isFinite(v)||Math.abs(v)>999_999_999_999_999||!Number.isSafeInteger(v*1_000_000))throw new ManagementContractError(f);return v}
function instant(v:unknown,f:string):string{const x=txt(v,f,64,10),n=Date.parse(x);if(!Number.isFinite(n))throw new ManagementContractError(f);return new Date(n).toISOString()}
function page<T>(v:unknown,p:(x:unknown)=>T):UuidPage<T>{const x=obj(v,"page");keys(x,["items","nextCursor"],"page");if(!Array.isArray(x.items)||x.items.length>100)throw new ManagementContractError("items");return {items:x.items.map(p),nextCursor:x.nextCursor===null?null:id(x.nextCursor,"nextCursor")}}
export function parseCustomer(v:unknown):CustomerSummary{const x=obj(v,"customer");keys(x,["id","code","displayName","email","phone","isActive","version","createdAt","updatedAt"],"customer");return {id:id(x.id,"id"),code:txt(x.code,"code",32),displayName:txt(x.displayName,"displayName",200),email:maybe(x.email,"email",254),phone:maybe(x.phone,"phone",32),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version"),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parseCustomerPage=(v:unknown)=>page(v,parseCustomer);
export function parseSupplier(v:unknown):SupplierSummary{const x=obj(v,"supplier");keys(x,["id","code","name","taxId","email","phone","isActive","version","createdAt","updatedAt"],"supplier");return {id:id(x.id,"id"),code:txt(x.code,"code",32),name:txt(x.name,"name",200),taxId:maybe(x.taxId,"taxId",64),email:maybe(x.email,"email",254),phone:maybe(x.phone,"phone",32),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version"),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parseSupplierPage=(v:unknown)=>page(v,parseSupplier);
export function parseEmployee(v:unknown):EmployeeSummary{const x=obj(v,"employee");keys(x,["id","branchId","code","displayName","email","phone","jobTitle","isActive","version","createdAt","updatedAt"],"employee");return {id:id(x.id,"id"),branchId:id(x.branchId,"branchId"),code:txt(x.code,"code",32),displayName:txt(x.displayName,"displayName",200),email:maybe(x.email,"email",254),phone:maybe(x.phone,"phone",32),jobTitle:txt(x.jobTitle,"jobTitle",120),isActive:bool(x.isActive,"isActive"),version:integer(x.version,"version"),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt")}}
export const parseEmployeePage=(v:unknown)=>page(v,parseEmployee);
function line(v:unknown):PurchaseOrderLineSummary{const x=obj(v,"line");keys(x,["productId","quantity","unitCost","lineTotal"],"line");const quantity=money(x.quantity,"quantity"),unitCost=money(x.unitCost,"unitCost"),lineTotal=money(x.lineTotal,"lineTotal");if(quantity<=0||unitCost<0||lineTotal<0)throw new ManagementContractError("line");return {productId:id(x.productId,"productId"),quantity,unitCost,lineTotal}}
export function parsePurchaseOrder(v:unknown):PurchaseOrderSummary{const x=obj(v,"order");keys(x,["id","branchId","supplierId","status","currency","reference","total","version","createdAt","updatedAt","lines"],"order");const status=txt(x.status,"status",16);if(!["draft","submitted","approved","cancelled"].includes(status))throw new ManagementContractError("status");const currency=txt(x.currency,"currency",3,3);if(!/^[A-Z]{3}$/u.test(currency)||!Array.isArray(x.lines)||x.lines.length>500)throw new ManagementContractError("order");return {id:id(x.id,"id"),branchId:id(x.branchId,"branchId"),supplierId:id(x.supplierId,"supplierId"),status:status as PurchaseOrderSummary["status"],currency,reference:maybe(x.reference,"reference",120),total:money(x.total,"total"),version:integer(x.version,"version"),createdAt:instant(x.createdAt,"createdAt"),updatedAt:instant(x.updatedAt,"updatedAt"),lines:x.lines.map(line)}}
export const parsePurchaseOrderPage=(v:unknown)=>page(v,parsePurchaseOrder);
export function parseOperationalReport(v:unknown):OperationalReportSummary{const x=obj(v,"report");keys(x,["organizationId","branchId","from","to","currency","salesCount","salesGross","returnCount","returnsTotal","netSales","purchaseOrderCount","purchaseOrderTotal","openShiftCount"],"report");const currency=x.currency===null?null:txt(x.currency,"currency",3,3);if(currency!==null&&!/^[A-Z]{3}$/u.test(currency))throw new ManagementContractError("currency");return {organizationId:id(x.organizationId,"organizationId"),branchId:id(x.branchId,"branchId"),from:instant(x.from,"from"),to:instant(x.to,"to"),currency,salesCount:integer(x.salesCount,"salesCount"),salesGross:money(x.salesGross,"salesGross"),returnCount:integer(x.returnCount,"returnCount"),returnsTotal:money(x.returnsTotal,"returnsTotal"),netSales:money(x.netSales,"netSales"),purchaseOrderCount:integer(x.purchaseOrderCount,"purchaseOrderCount"),purchaseOrderTotal:money(x.purchaseOrderTotal,"purchaseOrderTotal"),openShiftCount:integer(x.openShiftCount,"openShiftCount")}}
