<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Suppliers.Application/SalekhPos.Suppliers.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Suppliers.Domain/SalekhPos.Suppliers.Domain.csproj" />
    <ProjectReference Include="../SalekhPos.Suppliers.Contracts/SalekhPos.Suppliers.Contracts.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
