<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <ProjectReference Include="../../Modules/Identity/SalekhPos.Identity.Api/SalekhPos.Identity.Api.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <ProjectReference Include="../../BuildingBlocks/SalekhPos.SharedKernel/SalekhPos.SharedKernel.csproj" />
    <ProjectReference Include="../../Modules/Authorization/SalekhPos.Authorization.Infrastructure/SalekhPos.Authorization.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Catalog/SalekhPos.Catalog.Api/SalekhPos.Catalog.Api.csproj" />
    <ProjectReference Include="../../Modules/Catalog/SalekhPos.Catalog.Infrastructure/SalekhPos.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Stores/SalekhPos.Stores.Api/SalekhPos.Stores.Api.csproj" />
    <ProjectReference Include="../../Modules/Stores/SalekhPos.Stores.Infrastructure/SalekhPos.Stores.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/ShiftManagement/SalekhPos.ShiftManagement.Api/SalekhPos.ShiftManagement.Api.csproj" />
    <ProjectReference Include="../../Modules/ShiftManagement/SalekhPos.ShiftManagement.Infrastructure/SalekhPos.ShiftManagement.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Inventory/SalekhPos.Inventory.Api/SalekhPos.Inventory.Api.csproj" />
    <ProjectReference Include="../../Modules/Inventory/SalekhPos.Inventory.Infrastructure/SalekhPos.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Pricing/SalekhPos.Pricing.Api/SalekhPos.Pricing.Api.csproj" />
    <ProjectReference Include="../../Modules/Pricing/SalekhPos.Pricing.Infrastructure/SalekhPos.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Sales/SalekhPos.Sales.Api/SalekhPos.Sales.Api.csproj" />
    <ProjectReference Include="../../Modules/Sales/SalekhPos.Sales.Infrastructure/SalekhPos.Sales.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/Identity/SalekhPos.Identity.Infrastructure/SalekhPos.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../../Modules/SystemAdministration/SalekhPos.SystemAdministration.Api/SalekhPos.SystemAdministration.Api.csproj" />
    <ProjectReference Include="../../Modules/SystemAdministration/SalekhPos.SystemAdministration.Infrastructure/SalekhPos.SystemAdministration.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Payments\SalekhPos.Payments.Api\SalekhPos.Payments.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\SalekhPos.Payments.Infrastructure\SalekhPos.Payments.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Returns\SalekhPos.Returns.Api\SalekhPos.Returns.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Returns\SalekhPos.Returns.Infrastructure\SalekhPos.Returns.Infrastructure.csproj" />
  </ItemGroup>
</Project>
