<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Stores.Application/SalekhPos.Stores.Application.csproj" /><ProjectReference Include="../SalekhPos.Stores.Contracts/SalekhPos.Stores.Contracts.csproj" /></ItemGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup></Project>
