<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../SalekhPos.Support.Application/SalekhPos.Support.Application.csproj" /><ProjectReference Include="../SalekhPos.Support.Domain/SalekhPos.Support.Domain.csproj" /><ProjectReference Include="../SalekhPos.Support.Contracts/SalekhPos.Support.Contracts.csproj" /><PackageReference Include="Npgsql" /></ItemGroup></Project>
