<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Returns.Application/SalekhPos.Returns.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Returns.Contracts/SalekhPos.Returns.Contracts.csproj" />
    <ProjectReference Include="../SalekhPos.Returns.Domain/SalekhPos.Returns.Domain.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
