using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Npgsql;
using NpgsqlTypes;
using SalekhPos.Sync.Application.SyncMessages;
using SalekhPos.Sync.Contracts.SyncMessages;
using SalekhPos.Sync.Domain.SyncMessages;
namespace SalekhPos.Sync.Infrastructure.SyncMessages;

public sealed class PostgresSyncIngestion(NpgsqlDataSource? source) : ISyncIngestion
{
    public async Task<SyncAcknowledgementResponse> IngestAsync(SyncIdentity identity, IngestSyncMessageCommand x, CancellationToken ct)
    {
        var envelope = new SyncEnvelope(x.MessageId, x.DeviceId, x.Sequence, x.ProtocolVersion, x.MessageType, x.Payload); Validate(identity, x.OrganizationId, x.BranchId, x.DeviceId);
        var digest = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x.Payload))); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, x.OrganizationId, x.BranchId, ct);
        await using (var l = new NpgsqlCommand("SELECT pg_advisory_xact_lock(hashtextextended($1,0))", c, t)) { l.Parameters.AddWithValue($"{x.OrganizationId:D}:{x.DeviceId:D}"); await l.ExecuteNonQueryAsync(ct); }
        if (!await ActiveDevice(c, t, identity, x.OrganizationId, x.BranchId, x.DeviceId, x.ProtocolVersion, ct)) throw new SyncConflictException();
        var replay = await ByMessage(c, t, x.OrganizationId, x.MessageId, ct); if (replay is not null) { if (replay.DeviceId != x.DeviceId || replay.Sequence != x.Sequence || replay.ProtocolVersion != x.ProtocolVersion || replay.MessageType != x.MessageType || replay.PayloadDigest != digest) throw new SyncConflictException(); await t.CommitAsync(ct); return replay with { Replay = true }; }
        var last = await LastSequence(c, t, x.OrganizationId, x.DeviceId, ct); if (x.Sequence != last + 1) throw new SyncConflictException(); var at = await Time(c, t, ct);
        try { await using var q = new NpgsqlCommand("INSERT INTO sync.ingested_messages(organization_id,branch_id,device_id,message_id,sequence,protocol_version,message_type,payload_digest,payload,status,accepted_at,issuer,subject) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'accepted',$10,$11,$12)", c, t); q.Parameters.AddWithValue(x.OrganizationId); q.Parameters.AddWithValue(x.BranchId); q.Parameters.AddWithValue(x.DeviceId); q.Parameters.AddWithValue(x.MessageId); q.Parameters.AddWithValue(x.Sequence); q.Parameters.AddWithValue(x.ProtocolVersion); q.Parameters.AddWithValue(x.MessageType); q.Parameters.AddWithValue(digest); q.Parameters.AddWithValue(x.Payload); q.Parameters.AddWithValue(at); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); } catch (PostgresException e) when (e.SqlState == PostgresErrorCodes.UniqueViolation) { throw new SyncConflictException(); }
        var (status, code) = await Materialize(c, t, identity, x, envelope.Sale, at, ct);
        await using (var q = new NpgsqlCommand("INSERT INTO sync.message_results(organization_id,message_id,sale_id,status,result_code,decided_at) VALUES($1,$2,$3,$4,$5,$6)", c, t)) { q.Parameters.AddWithValue(x.OrganizationId); q.Parameters.AddWithValue(x.MessageId); q.Parameters.AddWithValue(envelope.Sale.SaleId); q.Parameters.AddWithValue(status); q.Parameters.AddWithValue(code); q.Parameters.AddWithValue(at); await q.ExecuteNonQueryAsync(ct); }
        await t.CommitAsync(ct); return new(x.MessageId, x.DeviceId, envelope.Sale.SaleId, x.Sequence, x.ProtocolVersion, x.MessageType, status, code, digest, at, false);
    }
    public async Task<SyncCheckpointResponse?> ReadCheckpointAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, CancellationToken ct) { Validate(identity, org, branch, device); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return null; } long seq; DateTimeOffset? at; await using (var q = new NpgsqlCommand("SELECT COALESCE(max(sequence),0),max(accepted_at) FROM sync.ingested_messages WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); seq = r.GetInt64(0); at = r.IsDBNull(1) ? null : r.GetFieldValue<DateTimeOffset>(1); } await t.CommitAsync(ct); return new(device, seq, at); }
    public async Task<SyncMessageResponse?> ReadMessageAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, Guid message, CancellationToken ct) { Validate(identity, org, branch, device); if (message == Guid.Empty) throw new ArgumentException("Message is required."); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return null; } SyncMessageResponse? result; await using (var q = new NpgsqlCommand("SELECT m.message_id,m.device_id,r.sale_id,m.sequence,m.protocol_version,m.message_type,coalesce(r.status,m.status),coalesce(r.result_code,m.status),m.payload_digest,m.accepted_at FROM sync.ingested_messages m LEFT JOIN sync.message_results r ON r.organization_id=m.organization_id AND r.message_id=m.message_id WHERE m.organization_id=$1 AND m.branch_id=$2 AND m.device_id=$3 AND m.message_id=$4", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(message); await using var r = await q.ExecuteReaderAsync(ct); result = await r.ReadAsync(ct) ? Message(r) : null; } await t.CommitAsync(ct); return result; }
    public async Task<SyncMessageHistoryResponse> ReadHistoryAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, int pageSize, long? after, CancellationToken ct) { Validate(identity, org, branch, device); if (pageSize is < 1 or > 100 || after is <= 0) throw new ArgumentException("Paging is invalid."); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return new([], null); } var rows = new List<SyncMessageResponse>(); await using (var q = new NpgsqlCommand("SELECT m.message_id,m.device_id,r.sale_id,m.sequence,m.protocol_version,m.message_type,coalesce(r.status,m.status),coalesce(r.result_code,m.status),m.payload_digest,m.accepted_at FROM sync.ingested_messages m LEFT JOIN sync.message_results r ON r.organization_id=m.organization_id AND r.message_id=m.message_id WHERE m.organization_id=$1 AND m.branch_id=$2 AND m.device_id=$3 AND ($4::bigint IS NULL OR m.sequence<$4) ORDER BY m.sequence DESC LIMIT $5", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(after ?? (object)DBNull.Value); q.Parameters.AddWithValue(pageSize + 1); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) rows.Add(Message(r)); } var more = rows.Count > pageSize; if (more) rows.RemoveAt(rows.Count - 1); await t.CommitAsync(ct); return new(rows, more ? rows[^1].Sequence : null); }
    private static SyncMessageResponse Message(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetGuid(1), r.IsDBNull(2) ? null : r.GetGuid(2), r.GetInt64(3), r.GetInt32(4), r.GetString(5), r.GetString(6), r.GetString(7), r.GetString(8), r.GetFieldValue<DateTimeOffset>(9));
    private static async Task<SyncAcknowledgementResponse?> ByMessage(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid message, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT m.message_id,m.device_id,r.sale_id,m.sequence,m.protocol_version,m.message_type,coalesce(r.status,m.status),coalesce(r.result_code,m.status),m.payload_digest,m.accepted_at FROM sync.ingested_messages m LEFT JOIN sync.message_results r ON r.organization_id=m.organization_id AND r.message_id=m.message_id WHERE m.organization_id=$1 AND m.message_id=$2", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(message); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(r.GetGuid(0), r.GetGuid(1), r.IsDBNull(2) ? null : r.GetGuid(2), r.GetInt64(3), r.GetInt32(4), r.GetString(5), r.GetString(6), r.GetString(7), r.GetString(8), r.GetFieldValue<DateTimeOffset>(9), false) : null; }
    private static async Task<long> LastSequence(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid device, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT COALESCE(max(sequence),0) FROM sync.ingested_messages WHERE organization_id=$1 AND device_id=$2", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(device); return (long)(await q.ExecuteScalarAsync(ct) ?? 0L); }
    private static async Task<(string Status, string Code)> Materialize(NpgsqlConnection c, NpgsqlTransaction t,
        SyncIdentity identity, IngestSyncMessageCommand command, OfflineCompletedSale sale, DateTimeOffset decidedAt,
        CancellationToken ct)
    {
        await Demand(c, t, identity, command.OrganizationId, command.BranchId, "sales.complete", ct);
        await Lock(c, t, $"{command.OrganizationId:D}:{sale.ShiftId:D}", ct);
        if (sale.CompletedAt > decidedAt.AddMinutes(5)) return ("rejected", "sale_conflict");
        await using (var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM shifts.shifts s JOIN stores.registers r ON r.organization_id=s.organization_id AND r.branch_id=s.branch_id AND r.register_id=s.register_id AND r.is_active JOIN devices.registered_devices d ON d.organization_id=s.organization_id AND d.branch_id=s.branch_id AND d.register_id=s.register_id AND d.device_id=$4 WHERE s.organization_id=$1 AND s.branch_id=$2 AND s.shift_id=$3 AND s.register_id=$5 AND s.currency=$6 AND s.status='open' AND s.opened_at<=$7)", c, t))
        { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(command.BranchId); q.Parameters.AddWithValue(sale.ShiftId); q.Parameters.AddWithValue(command.DeviceId); q.Parameters.AddWithValue(sale.RegisterId); q.Parameters.AddWithValue(sale.Currency); q.Parameters.AddWithValue(sale.CompletedAt); if (await q.ExecuteScalarAsync(ct) is not true) return ("rejected", "shift_conflict"); }
        await using (var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM sales.completed_sales WHERE organization_id=$1 AND (sale_id=$2 OR operation_id=$3))", c, t))
        { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(sale.SaleId); q.Parameters.AddWithValue(command.MessageId); if (await q.ExecuteScalarAsync(ct) is true) return ("rejected", "sale_conflict"); }
        foreach (var line in sale.Lines.OrderBy(x => x.ProductId)) await Lock(c, t, $"stock:{command.OrganizationId:D}:{command.BranchId:D}:{line.ProductId:D}", ct);
        foreach (var line in sale.Lines)
        {
            await using (var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM pricing.prices p JOIN catalog.products x ON x.organization_id=p.organization_id AND x.product_id=p.product_id AND x.is_active WHERE p.organization_id=$1 AND p.price_id=$2 AND p.product_id=$3 AND (p.branch_id=$4 OR p.branch_id IS NULL) AND p.amount=$5 AND p.currency=$6 AND p.tax_mode=$7 AND p.tax_rate=$8 AND p.valid_from<=$9 AND (p.valid_until IS NULL OR p.valid_until>$9))", c, t))
            { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(line.PriceId); q.Parameters.AddWithValue(line.ProductId); q.Parameters.AddWithValue(command.BranchId); q.Parameters.AddWithValue(line.UnitAmount); q.Parameters.AddWithValue(sale.Currency); q.Parameters.AddWithValue(line.TaxMode); q.Parameters.AddWithValue(line.TaxRate); q.Parameters.AddWithValue(sale.CompletedAt); if (await q.ExecuteScalarAsync(ct) is not true) return ("rejected", "price_conflict"); }
            await using var stock = new NpgsqlCommand("SELECT coalesce(sum(direction*quantity),0)::numeric(20,6) FROM inventory.stock_movements WHERE organization_id=$1 AND branch_id=$2 AND product_id=$3", c, t);
            stock.Parameters.AddWithValue(command.OrganizationId); stock.Parameters.AddWithValue(command.BranchId); stock.Parameters.AddWithValue(line.ProductId);
            if ((decimal)(await stock.ExecuteScalarAsync(ct) ?? 0m) < line.Quantity) return ("rejected", "insufficient_stock");
        }
        await t.SaveAsync("offline_sale", ct);
        try
        {
            await using (var q = new NpgsqlCommand("INSERT INTO sales.completed_sales(organization_id,sale_id,operation_id,branch_id,shift_id,register_id,currency,net_total,tax_total,grand_total,cash_received,change_due,completed_at,issuer,subject) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)", c, t))
            { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(sale.SaleId); q.Parameters.AddWithValue(command.MessageId); q.Parameters.AddWithValue(command.BranchId); q.Parameters.AddWithValue(sale.ShiftId); q.Parameters.AddWithValue(sale.RegisterId); q.Parameters.AddWithValue(sale.Currency); q.Parameters.AddWithValue(sale.NetTotal); q.Parameters.AddWithValue(sale.TaxTotal); q.Parameters.AddWithValue(sale.GrandTotal); q.Parameters.AddWithValue(sale.CashReceived); q.Parameters.AddWithValue(sale.ChangeDue); q.Parameters.AddWithValue(sale.CompletedAt); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); }
            for (var index = 0; index < sale.Lines.Count; index++)
            {
                var line = sale.Lines[index]; var movement = Guid.NewGuid(); var operation = Guid.NewGuid();
                await using (var q = new NpgsqlCommand("INSERT INTO inventory.stock_movements(organization_id,movement_id,operation_id,branch_id,product_id,kind,direction,quantity,reason,occurred_at,issuer,subject) VALUES($1,$2,$3,$4,$5,'sale',-1,$6,'Synchronized offline cash sale',$7,$8,$9)", c, t))
                { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(movement); q.Parameters.AddWithValue(operation); q.Parameters.AddWithValue(command.BranchId); q.Parameters.AddWithValue(line.ProductId); q.Parameters.AddWithValue(line.Quantity); q.Parameters.AddWithValue(sale.CompletedAt); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); }
                await using (var q = new NpgsqlCommand("INSERT INTO sales.sale_lines(organization_id,sale_id,line_number,product_id,price_id,inventory_movement_id,inventory_operation_id,quantity,unit_amount,currency,tax_mode,tax_rate,net_amount,tax_amount,gross_amount) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)", c, t))
                { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(sale.SaleId); q.Parameters.AddWithValue(index + 1); q.Parameters.AddWithValue(line.ProductId); q.Parameters.AddWithValue(line.PriceId); q.Parameters.AddWithValue(movement); q.Parameters.AddWithValue(operation); q.Parameters.AddWithValue(line.Quantity); q.Parameters.AddWithValue(line.UnitAmount); q.Parameters.AddWithValue(sale.Currency); q.Parameters.AddWithValue(line.TaxMode); q.Parameters.AddWithValue(line.TaxRate); q.Parameters.AddWithValue(line.NetAmount); q.Parameters.AddWithValue(line.TaxAmount); q.Parameters.AddWithValue(line.GrossAmount); await q.ExecuteNonQueryAsync(ct); }
            }
            var payload = JsonSerializer.Serialize(new { saleId = sale.SaleId, organizationId = command.OrganizationId, branchId = command.BranchId, sale.Currency, sale.GrandTotal, sale.CompletedAt, sale.Lines });
            await using (var q = new NpgsqlCommand("INSERT INTO sales.outbox_messages(organization_id,message_id,sale_id,event_type,payload,occurred_at) VALUES($1,$2,$3,'sales.sale_completed.v1',$4,$5)", c, t))
            { q.Parameters.AddWithValue(command.OrganizationId); q.Parameters.AddWithValue(Guid.NewGuid()); q.Parameters.AddWithValue(sale.SaleId); q.Parameters.Add(new NpgsqlParameter { NpgsqlDbType = NpgsqlDbType.Jsonb, Value = payload }); q.Parameters.AddWithValue(sale.CompletedAt); await q.ExecuteNonQueryAsync(ct); }
            return ("applied", "applied");
        }
        catch (PostgresException exception) when (exception.SqlState.StartsWith("23", StringComparison.Ordinal))
        {
            await t.RollbackAsync("offline_sale", ct); return ("rejected", "sale_conflict");
        }
    }
    private static async Task Lock(NpgsqlConnection c, NpgsqlTransaction t, string key, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT pg_advisory_xact_lock(hashtextextended($1,0))", c, t); q.Parameters.AddWithValue(key); await q.ExecuteNonQueryAsync(ct); }
    private static async Task<bool> ActiveDevice(NpgsqlConnection c, NpgsqlTransaction t, SyncIdentity identity, Guid org, Guid branch, Guid device, int protocol, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM devices.registered_devices WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3 AND status='active' AND sync_protocol_version=$4 AND issuer=$5 AND registered_by=$6)", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(protocol); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); return await q.ExecuteScalarAsync(ct) is true; }
    private static async Task<DateTimeOffset> Time(NpgsqlConnection c, NpgsqlTransaction t, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT statement_timestamp()", c, t); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new SyncUnavailableException(); return r.GetFieldValue<DateTimeOffset>(0); }
    private static void Validate(SyncIdentity i, Guid org, Guid branch, Guid device) { if (org == Guid.Empty || branch == Guid.Empty || device == Guid.Empty || string.IsNullOrWhiteSpace(i.Issuer) || string.IsNullOrWhiteSpace(i.Subject)) throw new ArgumentException("Sync request is invalid."); }
    private static Task Demand(NpgsqlConnection c, NpgsqlTransaction t, SyncIdentity i, Guid org, Guid branch, CancellationToken ct) => Demand(c, t, i, org, branch, "sync.ingest", ct);
    private static async Task Demand(NpgsqlConnection c, NpgsqlTransaction t, SyncIdentity i, Guid org, Guid branch, string permission, CancellationToken ct) { await using (var q = new NpgsqlCommand("SELECT set_config('app.organization_id',$1,true),set_config('app.issuer',$2,true),set_config('app.subject',$3,true)", c, t)) { q.Parameters.AddWithValue(org.ToString()); q.Parameters.AddWithValue(i.Issuer); q.Parameters.AddWithValue(i.Subject); await q.ExecuteNonQueryAsync(ct); } await using var d = new NpgsqlCommand("SELECT EXISTS(SELECT FROM access.memberships m JOIN access.permission_grants g ON g.organization_id=m.organization_id AND g.membership_id=m.membership_id JOIN organization.branches b ON b.organization_id=m.organization_id AND b.branch_id=$2 JOIN organization.businesses z ON z.organization_id=b.organization_id AND z.business_id=b.business_id JOIN organization.organizations a ON a.organization_id=b.organization_id WHERE m.organization_id=$1 AND m.issuer=$3 AND m.subject=$4 AND m.is_active AND b.is_active AND z.is_active AND a.is_active AND m.valid_from<=statement_timestamp() AND (m.valid_until IS NULL OR m.valid_until>statement_timestamp()) AND g.permission=$5 AND (g.scope_kind='organization' OR (g.scope_kind='business' AND g.business_id=b.business_id) OR (g.scope_kind='region' AND g.business_id=b.business_id AND g.region_id=b.region_id) OR (g.scope_kind='branch' AND g.business_id=b.business_id AND g.branch_id=b.branch_id)))", c, t); d.Parameters.AddWithValue(org); d.Parameters.AddWithValue(branch); d.Parameters.AddWithValue(i.Issuer); d.Parameters.AddWithValue(i.Subject); d.Parameters.AddWithValue(permission); if (await d.ExecuteScalarAsync(ct) is not true) throw new SyncDeniedException(); }
}
