using System.Security.Cryptography;
using System.Text;
using Npgsql;
using SalekhPos.Sync.Application.SyncMessages;
using SalekhPos.Sync.Contracts.SyncMessages;
using SalekhPos.Sync.Domain.SyncMessages;
namespace SalekhPos.Sync.Infrastructure.SyncMessages;

public sealed class PostgresSyncIngestion(NpgsqlDataSource? source) : ISyncIngestion
{
    public async Task<SyncAcknowledgementResponse> IngestAsync(SyncIdentity identity, IngestSyncMessageCommand x, CancellationToken ct)
    {
        _ = new SyncEnvelope(x.MessageId, x.DeviceId, x.Sequence, x.ProtocolVersion, x.MessageType, x.Payload); Validate(identity, x.OrganizationId, x.BranchId, x.DeviceId);
        var digest = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x.Payload))); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, x.OrganizationId, x.BranchId, ct);
        await using (var l = new NpgsqlCommand("SELECT pg_advisory_xact_lock(hashtextextended($1,0))", c, t)) { l.Parameters.AddWithValue($"{x.OrganizationId:D}:{x.DeviceId:D}"); await l.ExecuteNonQueryAsync(ct); }
        var replay = await ByMessage(c, t, x.OrganizationId, x.MessageId, ct); if (replay is not null) { if (replay.DeviceId != x.DeviceId || replay.Sequence != x.Sequence || replay.ProtocolVersion != x.ProtocolVersion || replay.MessageType != x.MessageType || replay.PayloadDigest != digest) throw new SyncConflictException(); await t.CommitAsync(ct); return replay with { Replay = true }; }
        if (!await ActiveDevice(c, t, identity, x.OrganizationId, x.BranchId, x.DeviceId, x.ProtocolVersion, ct)) throw new SyncConflictException();
        var last = await LastSequence(c, t, x.OrganizationId, x.DeviceId, ct); if (x.Sequence != last + 1) throw new SyncConflictException(); var at = await Time(c, t, ct);
        try { await using var q = new NpgsqlCommand("INSERT INTO sync.ingested_messages(organization_id,branch_id,device_id,message_id,sequence,protocol_version,message_type,payload_digest,payload,status,accepted_at,issuer,subject) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'accepted',$10,$11,$12)", c, t); q.Parameters.AddWithValue(x.OrganizationId); q.Parameters.AddWithValue(x.BranchId); q.Parameters.AddWithValue(x.DeviceId); q.Parameters.AddWithValue(x.MessageId); q.Parameters.AddWithValue(x.Sequence); q.Parameters.AddWithValue(x.ProtocolVersion); q.Parameters.AddWithValue(x.MessageType); q.Parameters.AddWithValue(digest); q.Parameters.AddWithValue(x.Payload); q.Parameters.AddWithValue(at); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); await q.ExecuteNonQueryAsync(ct); } catch (PostgresException e) when (e.SqlState == PostgresErrorCodes.UniqueViolation) { throw new SyncConflictException(); }
        await t.CommitAsync(ct); return new(x.MessageId, x.DeviceId, x.Sequence, x.ProtocolVersion, x.MessageType, "accepted", digest, at, false);
    }
    public async Task<SyncCheckpointResponse?> ReadCheckpointAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, CancellationToken ct) { Validate(identity, org, branch, device); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return null; } long seq; DateTimeOffset? at; await using (var q = new NpgsqlCommand("SELECT COALESCE(max(sequence),0),max(accepted_at) FROM sync.ingested_messages WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); await using var r = await q.ExecuteReaderAsync(ct); await r.ReadAsync(ct); seq = r.GetInt64(0); at = r.IsDBNull(1) ? null : r.GetFieldValue<DateTimeOffset>(1); } await t.CommitAsync(ct); return new(device, seq, at); }
    public async Task<SyncMessageResponse?> ReadMessageAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, Guid message, CancellationToken ct) { Validate(identity, org, branch, device); if (message == Guid.Empty) throw new ArgumentException("Message is required."); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return null; } SyncMessageResponse? result; await using (var q = new NpgsqlCommand("SELECT message_id,device_id,sequence,protocol_version,message_type,status,payload_digest,accepted_at FROM sync.ingested_messages WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3 AND message_id=$4", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(message); await using var r = await q.ExecuteReaderAsync(ct); result = await r.ReadAsync(ct) ? Message(r) : null; } await t.CommitAsync(ct); return result; }
    public async Task<SyncMessageHistoryResponse> ReadHistoryAsync(SyncIdentity identity, Guid org, Guid branch, Guid device, int pageSize, long? after, CancellationToken ct) { Validate(identity, org, branch, device); if (pageSize is < 1 or > 100 || after is <= 0) throw new ArgumentException("Paging is invalid."); var ds = source ?? throw new SyncUnavailableException(); await using var c = await ds.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await Demand(c, t, identity, org, branch, ct); if (!await ActiveDevice(c, t, identity, org, branch, device, 1, ct)) { await t.CommitAsync(ct); return new([], null); } var rows = new List<SyncMessageResponse>(); await using (var q = new NpgsqlCommand("SELECT message_id,device_id,sequence,protocol_version,message_type,status,payload_digest,accepted_at FROM sync.ingested_messages WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3 AND ($4::bigint IS NULL OR sequence<$4) ORDER BY sequence DESC LIMIT $5", c, t)) { q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(after ?? (object)DBNull.Value); q.Parameters.AddWithValue(pageSize + 1); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) rows.Add(Message(r)); } var more = rows.Count > pageSize; if (more) rows.RemoveAt(rows.Count - 1); await t.CommitAsync(ct); return new(rows, more ? rows[^1].Sequence : null); }
    private static SyncMessageResponse Message(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetGuid(1), r.GetInt64(2), r.GetInt32(3), r.GetString(4), r.GetString(5), r.GetString(6), r.GetFieldValue<DateTimeOffset>(7));
    private static async Task<SyncAcknowledgementResponse?> ByMessage(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid message, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT message_id,device_id,sequence,protocol_version,message_type,status,payload_digest,accepted_at FROM sync.ingested_messages WHERE organization_id=$1 AND message_id=$2", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(message); await using var r = await q.ExecuteReaderAsync(ct); return await r.ReadAsync(ct) ? new(r.GetGuid(0), r.GetGuid(1), r.GetInt64(2), r.GetInt32(3), r.GetString(4), r.GetString(5), r.GetString(6), r.GetFieldValue<DateTimeOffset>(7), false) : null; }
    private static async Task<long> LastSequence(NpgsqlConnection c, NpgsqlTransaction t, Guid org, Guid device, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT COALESCE(max(sequence),0) FROM sync.ingested_messages WHERE organization_id=$1 AND device_id=$2", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(device); return (long)(await q.ExecuteScalarAsync(ct) ?? 0L); }
    private static async Task<bool> ActiveDevice(NpgsqlConnection c, NpgsqlTransaction t, SyncIdentity identity, Guid org, Guid branch, Guid device, int protocol, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT EXISTS(SELECT FROM devices.registered_devices WHERE organization_id=$1 AND branch_id=$2 AND device_id=$3 AND status='active' AND sync_protocol_version=$4 AND issuer=$5 AND registered_by=$6)", c, t); q.Parameters.AddWithValue(org); q.Parameters.AddWithValue(branch); q.Parameters.AddWithValue(device); q.Parameters.AddWithValue(protocol); q.Parameters.AddWithValue(identity.Issuer); q.Parameters.AddWithValue(identity.Subject); return await q.ExecuteScalarAsync(ct) is true; }
    private static async Task<DateTimeOffset> Time(NpgsqlConnection c, NpgsqlTransaction t, CancellationToken ct) { await using var q = new NpgsqlCommand("SELECT statement_timestamp()", c, t); await using var r = await q.ExecuteReaderAsync(ct); if (!await r.ReadAsync(ct)) throw new SyncUnavailableException(); return r.GetFieldValue<DateTimeOffset>(0); }
    private static void Validate(SyncIdentity i, Guid org, Guid branch, Guid device) { if (org == Guid.Empty || branch == Guid.Empty || device == Guid.Empty || string.IsNullOrWhiteSpace(i.Issuer) || string.IsNullOrWhiteSpace(i.Subject)) throw new ArgumentException("Sync request is invalid."); }
    private static async Task Demand(NpgsqlConnection c, NpgsqlTransaction t, SyncIdentity i, Guid org, Guid branch, CancellationToken ct) { await using (var q = new NpgsqlCommand("SELECT set_config('app.organization_id',$1,true),set_config('app.issuer',$2,true),set_config('app.subject',$3,true)", c, t)) { q.Parameters.AddWithValue(org.ToString()); q.Parameters.AddWithValue(i.Issuer); q.Parameters.AddWithValue(i.Subject); await q.ExecuteNonQueryAsync(ct); } await using var d = new NpgsqlCommand("SELECT EXISTS(SELECT FROM access.memberships m JOIN access.permission_grants g ON g.organization_id=m.organization_id AND g.membership_id=m.membership_id JOIN organization.branches b ON b.organization_id=m.organization_id AND b.branch_id=$2 JOIN organization.businesses z ON z.organization_id=b.organization_id AND z.business_id=b.business_id JOIN organization.organizations a ON a.organization_id=b.organization_id WHERE m.organization_id=$1 AND m.issuer=$3 AND m.subject=$4 AND m.is_active AND b.is_active AND z.is_active AND a.is_active AND m.valid_from<=statement_timestamp() AND (m.valid_until IS NULL OR m.valid_until>statement_timestamp()) AND g.permission='sync.ingest' AND (g.scope_kind='organization' OR (g.scope_kind='business' AND g.business_id=b.business_id) OR (g.scope_kind='region' AND g.business_id=b.business_id AND g.region_id=b.region_id) OR (g.scope_kind='branch' AND g.business_id=b.business_id AND g.branch_id=b.branch_id)))", c, t); d.Parameters.AddWithValue(org); d.Parameters.AddWithValue(branch); d.Parameters.AddWithValue(i.Issuer); d.Parameters.AddWithValue(i.Subject); if (await d.ExecuteScalarAsync(ct) is not true) throw new SyncDeniedException(); }
}
