import type { SupportedLocale } from "./localization";

const en = {
  "app.name": "SalekhPos",
  "common.retry": "Try again",
  "common.back": "Back",
  "common.loading": "Loading",
  "common.loadMore": "Load more",
  "common.save": "Save",
  "common.saving": "Saving…",
  "common.signOut": "Sign out",
  "error.title": "Something went wrong",
  "error.message": "The application could not continue safely.",
  "config.title": "Configuration required",
  "config.message": "Set a valid API environment and base URL before signing in.",
  "session.restoreError": "Your secure session could not be restored.",
  "signIn.title": "Secure sign in",
  "signIn.message": "Use your organization's approved identity provider to continue.",
  "signIn.pending": "Identity-provider sign in is not configured for this build.",
  "dashboard.title": "Dashboard",
  "dashboard.welcome": "Signed in as {name}",
  "dashboard.roles": "Assigned roles",
  "dashboard.noRoles": "No roles were supplied by the session.",
  "navigation.dashboard": "Dashboard",
  "navigation.organizations": "Organization",
  "navigation.stores": "Stores",
  "navigation.products": "Products",
  "navigation.inventory": "Inventory",
  "navigation.scanner": "Barcode scanner",
  "cache.stale": "Offline cached data from {time}. It may be outdated.",
  "apiError.cancelled": "The request was cancelled.",
  "apiError.offline": "The server cannot be reached. Check your connection and try again.",
  "apiError.unauthenticated": "Your session is no longer authorized. Sign in again.",
  "apiError.forbidden": "You do not have permission for this operation.",
  "apiError.not_found": "The requested record is unavailable.",
  "apiError.conflict": "This operation conflicts with current server data.",
  "apiError.invalid": "The server rejected the submitted values.",
  "apiError.unsafe_response": "The server response could not be verified safely.",
  "apiError.unavailable": "The operation is temporarily unavailable.",
  "organizations.title": "Organization workspace",
  "organizations.explanation": "This session is securely bound to one organization. Organization discovery is not exposed by the current API.",
  "organizations.current": "Current organization",
  "organizations.chooseStore": "Choose a store",
  "stores.title": "Stores",
  "stores.explanation": "Select one of the stores your server-side membership permits.",
  "stores.empty": "No permitted configured stores were returned.",
  "stores.selected": "Selected workspace store",
  "workspace.noBranch": "No store is selected.",
  "workspace.branch": "Store: {name}",
  "workspace.branchRequired": "Choose a store before using branch inventory.",
  "workspace.chooseBranch": "Choose a store",
  "products.title": "Products",
  "products.search": "Search loaded products",
  "products.searchPlaceholder": "Name, SKU, or barcode",
  "products.scan": "Scan barcode",
  "products.empty": "No products were returned.",
  "products.noMatches": "No loaded products match this search.",
  "products.barcodeNotFound": "No product was found for this barcode.",
  "products.scannedResult": "Scanned product",
  "products.noBarcode": "No barcode",
  "products.inactive": "Inactive",
  "inventory.title": "Inventory stock",
  "inventory.empty": "No stock items were returned.",
  "inventory.quantity": "Quantity: {quantity}",
  "inventory.receive": "Receive stock",
  "inventory.adjust": "Adjust stock",
  "movement.receiptTitle": "Receive stock",
  "movement.adjustmentTitle": "Adjust stock",
  "movement.increase": "Increase",
  "movement.decrease": "Decrease",
  "movement.productId": "Product UUID",
  "movement.quantity": "Quantity",
  "movement.reason": "Reason (optional)",
  "movement.onlineOnly": "This write is online-only. It is not queued or presented as synchronized while offline.",
  "movement.invalid": "Enter a valid product UUID, positive quantity with up to six decimals, and a reason under 200 characters.",
  "movement.completed": "The server recorded the inventory movement.",
  "scanner.title": "Barcode scanner",
  "scanner.explanation": "Camera access is requested only when you start scanning.",
  "scanner.start": "Start scanning",
  "scanner.permissionDenied": "Camera access was not granted.",
  "scanner.permissionSettings": "Camera access is disabled. Enable it in system settings.",
  "scanner.scanned": "Scanned barcode: {value}",
  "scanner.scanAgain": "Scan another barcode",
  "scanner.invalidBarcode": "This scan is not a supported numeric product barcode.",
} as const;

export type TranslationKey = keyof typeof en;
type TranslationTable = Readonly<Record<TranslationKey, string>>;

const az: TranslationTable = {
  "app.name": "SalekhPos",
  "common.retry": "Yenidən cəhd edin",
  "common.back": "Geri",
  "common.loading": "Yüklənir",
  "common.loadMore": "Daha çox yüklə",
  "common.save": "Yadda saxla",
  "common.saving": "Yadda saxlanılır…",
  "common.signOut": "Çıxış",
  "error.title": "Xəta baş verdi",
  "error.message": "Tətbiq təhlükəsiz şəkildə davam edə bilmədi.",
  "config.title": "Konfiqurasiya tələb olunur",
  "config.message": "Daxil olmadan əvvəl düzgün API mühiti və əsas URL təyin edin.",
  "session.restoreError": "Təhlükəsiz sessiyanız bərpa edilə bilmədi.",
  "signIn.title": "Təhlükəsiz giriş",
  "signIn.message": "Davam etmək üçün təşkilatınızın təsdiqlənmiş giriş xidmətindən istifadə edin.",
  "signIn.pending": "Bu yığım üçün giriş xidməti konfiqurasiya edilməyib.",
  "dashboard.title": "İdarə paneli",
  "dashboard.welcome": "{name} kimi daxil olmusunuz",
  "dashboard.roles": "Təyin edilmiş rollar",
  "dashboard.noRoles": "Sessiya tərəfindən rol təqdim edilməyib.",
  "navigation.dashboard": "İdarə paneli",
  "navigation.organizations": "Təşkilat",
  "navigation.stores": "Mağazalar",
  "navigation.products": "Məhsullar",
  "navigation.inventory": "Anbar",
  "navigation.scanner": "Barkod skaneri",
  "cache.stale": "{time} tarixli oflayn keş məlumatıdır. Köhnəlmiş ola bilər.",
  "apiError.cancelled": "Sorğu ləğv edildi.",
  "apiError.offline": "Serverə qoşulmaq olmur. Bağlantını yoxlayıb yenidən cəhd edin.",
  "apiError.unauthenticated": "Sessiyanız artıq səlahiyyətli deyil. Yenidən daxil olun.",
  "apiError.forbidden": "Bu əməliyyat üçün icazəniz yoxdur.",
  "apiError.not_found": "Tələb olunan qeyd mövcud deyil.",
  "apiError.conflict": "Bu əməliyyat serverdəki cari məlumatla ziddiyyət təşkil edir.",
  "apiError.invalid": "Server göndərilən dəyərləri qəbul etmədi.",
  "apiError.unsafe_response": "Server cavabı təhlükəsiz şəkildə yoxlanıla bilmədi.",
  "apiError.unavailable": "Əməliyyat müvəqqəti olaraq əlçatan deyil.",
  "organizations.title": "Təşkilat iş sahəsi",
  "organizations.explanation": "Bu sessiya təhlükəsiz şəkildə bir təşkilata bağlıdır. Cari API təşkilat axtarışını təqdim etmir.",
  "organizations.current": "Cari təşkilat",
  "organizations.chooseStore": "Mağaza seçin",
  "stores.title": "Mağazalar",
  "stores.explanation": "Server üzvlüyünüzün icazə verdiyi mağazalardan birini seçin.",
  "stores.empty": "İcazə verilmiş konfiqurasiya olunmuş mağaza qaytarılmadı.",
  "stores.selected": "Seçilmiş iş sahəsi mağazası",
  "workspace.noBranch": "Mağaza seçilməyib.",
  "workspace.branch": "Mağaza: {name}",
  "workspace.branchRequired": "Filial anbarından istifadə etməzdən əvvəl mağaza seçin.",
  "workspace.chooseBranch": "Mağaza seçin",
  "products.title": "Məhsullar",
  "products.search": "Yüklənmiş məhsullarda axtar",
  "products.searchPlaceholder": "Ad, SKU və ya barkod",
  "products.scan": "Barkodu skan et",
  "products.empty": "Məhsul qaytarılmadı.",
  "products.noMatches": "Yüklənmiş məhsullarda uyğun nəticə yoxdur.",
  "products.barcodeNotFound": "Bu barkod üçün məhsul tapılmadı.",
  "products.scannedResult": "Skan edilmiş məhsul",
  "products.noBarcode": "Barkod yoxdur",
  "products.inactive": "Deaktiv",
  "inventory.title": "Anbar qalığı",
  "inventory.empty": "Anbar mövqeyi qaytarılmadı.",
  "inventory.quantity": "Miqdar: {quantity}",
  "inventory.receive": "Mal qəbul et",
  "inventory.adjust": "Qalığı düzəlt",
  "movement.receiptTitle": "Mal qəbulu",
  "movement.adjustmentTitle": "Qalıq düzəlişi",
  "movement.increase": "Artır",
  "movement.decrease": "Azalt",
  "movement.productId": "Məhsul UUID-si",
  "movement.quantity": "Miqdar",
  "movement.reason": "Səbəb (istəyə bağlı)",
  "movement.onlineOnly": "Bu yazı yalnız onlayndır. Oflayn halda növbəyə alınmır və sinxronlaşdırılmış kimi göstərilmir.",
  "movement.invalid": "Düzgün məhsul UUID-si, altı onluq rəqəmə qədər müsbət miqdar və 200 simvoldan qısa səbəb daxil edin.",
  "movement.completed": "Server anbar hərəkətini qeydə aldı.",
  "scanner.title": "Barkod skaneri",
  "scanner.explanation": "Kamera icazəsi yalnız skanı başladanda istənilir.",
  "scanner.start": "Skanı başladın",
  "scanner.permissionDenied": "Kamera icazəsi verilmədi.",
  "scanner.permissionSettings": "Kamera girişi deaktivdir. Onu sistem ayarlarında aktiv edin.",
  "scanner.scanned": "Skan edilmiş barkod: {value}",
  "scanner.scanAgain": "Başqa barkod skan edin",
  "scanner.invalidBarcode": "Bu skan dəstəklənən rəqəmsal məhsul barkodu deyil.",
};

const ka: TranslationTable = {
  "app.name": "SalekhPos",
  "common.retry": "ხელახლა ცდა",
  "common.back": "უკან",
  "common.loading": "იტვირთება",
  "common.loadMore": "მეტის ჩატვირთვა",
  "common.save": "შენახვა",
  "common.saving": "ინახება…",
  "common.signOut": "გასვლა",
  "error.title": "დაფიქსირდა შეცდომა",
  "error.message": "აპლიკაციამ უსაფრთხოდ გაგრძელება ვერ შეძლო.",
  "config.title": "საჭიროა კონფიგურაცია",
  "config.message": "შესვლამდე მიუთითეთ სწორი API გარემო და საბაზისო URL.",
  "session.restoreError": "თქვენი დაცული სესიის აღდგენა ვერ მოხერხდა.",
  "signIn.title": "უსაფრთხო შესვლა",
  "signIn.message": "გასაგრძელებლად გამოიყენეთ თქვენი ორგანიზაციის დამტკიცებული ავტორიზაცია.",
  "signIn.pending": "ამ ვერსიისთვის ავტორიზაციის პროვაიდერი კონფიგურირებული არ არის.",
  "dashboard.title": "მართვის პანელი",
  "dashboard.welcome": "შესული ხართ როგორც {name}",
  "dashboard.roles": "მინიჭებული როლები",
  "dashboard.noRoles": "სესიას როლები არ მოჰყოლია.",
  "navigation.dashboard": "მართვის პანელი",
  "navigation.organizations": "ორგანიზაცია",
  "navigation.stores": "მაღაზიები",
  "navigation.products": "პროდუქტები",
  "navigation.inventory": "მარაგები",
  "navigation.scanner": "შტრიხკოდის სკანერი",
  "cache.stale": "ოფლაინ ქეშის მონაცემები {time}-დან. შესაძლოა მოძველებული იყოს.",
  "apiError.cancelled": "მოთხოვნა გაუქმდა.",
  "apiError.offline": "სერვერთან დაკავშირება ვერ ხერხდება. შეამოწმეთ კავშირი და სცადეთ კვლავ.",
  "apiError.unauthenticated": "თქვენი სესია აღარ არის ავტორიზებული. შედით თავიდან.",
  "apiError.forbidden": "ამ ოპერაციის ნებართვა არ გაქვთ.",
  "apiError.not_found": "მოთხოვნილი ჩანაწერი მიუწვდომელია.",
  "apiError.conflict": "ოპერაცია ეწინააღმდეგება სერვერის მიმდინარე მონაცემებს.",
  "apiError.invalid": "სერვერმა გაგზავნილი მნიშვნელობები უარყო.",
  "apiError.unsafe_response": "სერვერის პასუხის უსაფრთხოდ გადამოწმება ვერ მოხერხდა.",
  "apiError.unavailable": "ოპერაცია დროებით მიუწვდომელია.",
  "organizations.title": "ორგანიზაციის სამუშაო სივრცე",
  "organizations.explanation": "ეს სესია უსაფრთხოდ არის მიბმული ერთ ორგანიზაციაზე. მიმდინარე API ორგანიზაციების მოძიებას არ უზრუნველყოფს.",
  "organizations.current": "მიმდინარე ორგანიზაცია",
  "organizations.chooseStore": "მაღაზიის არჩევა",
  "stores.title": "მაღაზიები",
  "stores.explanation": "აირჩიეთ სერვერზე თქვენი წევრობით დაშვებული მაღაზია.",
  "stores.empty": "დაშვებული და კონფიგურირებული მაღაზია არ დაბრუნებულა.",
  "stores.selected": "არჩეული სამუშაო მაღაზია",
  "workspace.noBranch": "მაღაზია არჩეული არ არის.",
  "workspace.branch": "მაღაზია: {name}",
  "workspace.branchRequired": "ფილიალის მარაგის გამოყენებამდე აირჩიეთ მაღაზია.",
  "workspace.chooseBranch": "მაღაზიის არჩევა",
  "products.title": "პროდუქტები",
  "products.search": "ჩატვირთულ პროდუქტებში ძებნა",
  "products.searchPlaceholder": "სახელი, SKU ან შტრიხკოდი",
  "products.scan": "შტრიხკოდის სკანირება",
  "products.empty": "პროდუქტები არ დაბრუნებულა.",
  "products.noMatches": "ჩატვირთულ პროდუქტებში დამთხვევა არ არის.",
  "products.barcodeNotFound": "ამ შტრიხკოდით პროდუქტი ვერ მოიძებნა.",
  "products.scannedResult": "სკანირებული პროდუქტი",
  "products.noBarcode": "შტრიხკოდი არ აქვს",
  "products.inactive": "არააქტიური",
  "inventory.title": "მარაგის ნაშთი",
  "inventory.empty": "მარაგის ჩანაწერები არ დაბრუნებულა.",
  "inventory.quantity": "რაოდენობა: {quantity}",
  "inventory.receive": "მარაგის მიღება",
  "inventory.adjust": "მარაგის კორექტირება",
  "movement.receiptTitle": "მარაგის მიღება",
  "movement.adjustmentTitle": "მარაგის კორექტირება",
  "movement.increase": "გაზრდა",
  "movement.decrease": "შემცირება",
  "movement.productId": "პროდუქტის UUID",
  "movement.quantity": "რაოდენობა",
  "movement.reason": "მიზეზი (არასავალდებულო)",
  "movement.onlineOnly": "ეს ჩაწერა მხოლოდ ონლაინ მუშაობს. ოფლაინ რეჟიმში რიგში არ დგება და სინქრონიზებულად არ არის ნაჩვენები.",
  "movement.invalid": "შეიყვანეთ სწორი პროდუქტის UUID, დადებითი რაოდენობა მაქსიმუმ ექვსი ათწილადით და 200 სიმბოლოზე მოკლე მიზეზი.",
  "movement.completed": "სერვერმა მარაგის მოძრაობა ჩაწერა.",
  "scanner.title": "შტრიხკოდის სკანერი",
  "scanner.explanation": "კამერის ნებართვა მოითხოვება მხოლოდ სკანირების დაწყებისას.",
  "scanner.start": "სკანირების დაწყება",
  "scanner.permissionDenied": "კამერის ნებართვა არ გაიცა.",
  "scanner.permissionSettings": "კამერაზე წვდომა გამორთულია. ჩართეთ სისტემის პარამეტრებში.",
  "scanner.scanned": "სკანირებული შტრიხკოდი: {value}",
  "scanner.scanAgain": "სხვა შტრიხკოდის სკანირება",
  "scanner.invalidBarcode": "ეს სკანი მხარდაჭერილი ციფრული პროდუქტის შტრიხკოდი არ არის.",
};

export const resources: Readonly<Record<SupportedLocale, TranslationTable>> = {
  en,
  az,
  ka,
};

export function translate(
  locale: SupportedLocale,
  key: TranslationKey,
  values: Readonly<Record<string, string>> = {},
): string {
  const template = resources[locale][key] ?? resources.en[key];
  return template.replace(/\{(\w+)\}/gu, (_, name: string) => values[name] ?? `{${name}}`);
}
