import type { SupportedLocale } from "./localization";

const en = {
  "app.name": "SalekhPos",
  "common.retry": "Try again",
  "common.back": "Back",
  "common.loading": "Loading",
  "common.loadMore": "Load more",
  "common.save": "Save",
  "common.saving": "Savingâ€¦",
  "common.signOut": "Sign out",
  "error.title": "Something went wrong",
  "error.message": "The application could not continue safely.",
  "config.title": "Configuration required",
  "config.message": "Set a valid API environment and base URL before signing in.",
  "session.restoreError": "Your secure session could not be restored.",
  "signIn.title": "Secure sign in",
  "signIn.message": "Use your organization's approved identity provider to continue.",
  "signIn.pending": "Identity-provider sign in is not configured for this build.",
  "dashboard.title": "Dashboard",
  "dashboard.welcome": "Signed in as {name}",
  "dashboard.roles": "Assigned roles",
  "dashboard.noRoles": "No roles were supplied by the session.",
  "navigation.dashboard": "Dashboard",
  "navigation.organizations": "Organization",
  "navigation.stores": "Stores",
  "navigation.products": "Products",
  "navigation.inventory": "Inventory",
  "navigation.scanner": "Barcode scanner",
  "navigation.pricing": "Pricing",
  "navigation.registers": "Registers",
  "navigation.reconciliation": "Reconciliation",
  "navigation.customers": "Customers",
  "navigation.suppliers": "Suppliers",
  "navigation.employees": "Employees",
  "navigation.purchasing": "Purchasing",
  "navigation.reports": "Reports",
  "navigation.stockTransfers": "Stock transfers",
  "navigation.promotions": "Promotions",
  "navigation.loyalty": "Loyalty",
  "navigation.audit": "Audit",
  "management.customers": "Customers",
  "management.suppliers": "Suppliers",
  "management.employees": "Employees",
  "management.purchasing": "Purchase orders",
  "management.reports": "Operational report",
  "pricing.title": "Pricing",
  "pricing.explanation": "Review effective prices and schedule authorized price changes.",
  "registers.title": "Registers",
  "registers.explanation": "Review branch registers and provision new authorized registers.",
  "reconciliation.title": "Reconciliation",
  "reconciliation.explanation": "Monitor open and closed shifts together with payment events.",
  "reconciliation.trustedBoundary": "Shift opening, cash movement writes, and shift closing remain trusted-terminal operations.",
  "cache.stale": "Offline cached data from {time}. It may be outdated.",
  "apiError.cancelled": "The request was cancelled.",
  "apiError.offline": "The server cannot be reached. Check your connection and try again.",
  "apiError.unauthenticated": "Your session is no longer authorized. Sign in again.",
  "apiError.forbidden": "You do not have permission for this operation.",
  "apiError.not_found": "The requested record is unavailable.",
  "apiError.conflict": "This operation conflicts with current server data.",
  "apiError.invalid": "The server rejected the submitted values.",
  "apiError.unsafe_response": "The server response could not be verified safely.",
  "apiError.unavailable": "The operation is temporarily unavailable.",
  "organizations.title": "Organization workspace",
  "organizations.explanation": "This session is securely bound to one organization. Organization discovery is not exposed by the current API.",
  "organizations.current": "Current organization",
  "organizations.chooseStore": "Choose a store",
  "stores.title": "Stores",
  "stores.explanation": "Select one of the stores your server-side membership permits.",
  "stores.empty": "No permitted configured stores were returned.",
  "stores.selected": "Selected workspace store",
  "workspace.noBranch": "No store is selected.",
  "workspace.branch": "Store: {name}",
  "workspace.branchRequired": "Choose a store before using branch inventory.",
  "workspace.chooseBranch": "Choose a store",
  "products.title": "Products",
  "products.search": "Search loaded products",
  "products.searchPlaceholder": "Name, SKU, or barcode",
  "products.scan": "Scan barcode",
  "products.empty": "No products were returned.",
  "products.noMatches": "No loaded products match this search.",
  "products.barcodeNotFound": "No product was found for this barcode.",
  "products.scannedResult": "Scanned product",
  "products.noBarcode": "No barcode",
  "products.inactive": "Inactive",
  "inventory.title": "Inventory stock",
  "inventory.empty": "No stock items were returned.",
  "inventory.quantity": "Quantity: {quantity}",
  "inventory.receive": "Receive stock",
  "inventory.adjust": "Adjust stock",
  "movement.receiptTitle": "Receive stock",
  "movement.adjustmentTitle": "Adjust stock",
  "movement.increase": "Increase",
  "movement.decrease": "Decrease",
  "movement.productId": "Product UUID",
  "movement.quantity": "Quantity",
  "movement.reason": "Reason (optional)",
  "movement.onlineOnly": "This write is online-only. It is not queued or presented as synchronized while offline.",
  "movement.invalid": "Enter a valid product UUID, positive quantity with up to six decimals, and a reason under 200 characters.",
  "movement.completed": "The server recorded the inventory movement.",
  "scanner.title": "Barcode scanner",
  "scanner.explanation": "Camera access is requested only when you start scanning.",
  "scanner.start": "Start scanning",
  "scanner.permissionDenied": "Camera access was not granted.",
  "scanner.permissionSettings": "Camera access is disabled. Enable it in system settings.",
  "scanner.scanned": "Scanned barcode: {value}",
  "scanner.scanAgain": "Scan another barcode",
  "scanner.invalidBarcode": "This scan is not a supported numeric product barcode.",
} as const;

export type TranslationKey = keyof typeof en;
type TranslationTable = Readonly<Record<TranslationKey, string>>;

const az: TranslationTable = {
  "app.name": "SalekhPos",
  "common.retry": "YenidÉ™n cÉ™hd edin",
  "common.back": "Geri",
  "common.loading": "YÃ¼klÉ™nir",
  "common.loadMore": "Daha Ã§ox yÃ¼klÉ™",
  "common.save": "Yadda saxla",
  "common.saving": "Yadda saxlanÄ±lÄ±râ€¦",
  "common.signOut": "Ã‡Ä±xÄ±ÅŸ",
  "error.title": "XÉ™ta baÅŸ verdi",
  "error.message": "TÉ™tbiq tÉ™hlÃ¼kÉ™siz ÅŸÉ™kildÉ™ davam edÉ™ bilmÉ™di.",
  "config.title": "Konfiqurasiya tÉ™lÉ™b olunur",
  "config.message": "Daxil olmadan É™vvÉ™l dÃ¼zgÃ¼n API mÃ¼hiti vÉ™ É™sas URL tÉ™yin edin.",
  "session.restoreError": "TÉ™hlÃ¼kÉ™siz sessiyanÄ±z bÉ™rpa edilÉ™ bilmÉ™di.",
  "signIn.title": "TÉ™hlÃ¼kÉ™siz giriÅŸ",
  "signIn.message": "Davam etmÉ™k Ã¼Ã§Ã¼n tÉ™ÅŸkilatÄ±nÄ±zÄ±n tÉ™sdiqlÉ™nmiÅŸ giriÅŸ xidmÉ™tindÉ™n istifadÉ™ edin.",
  "signIn.pending": "Bu yÄ±ÄŸÄ±m Ã¼Ã§Ã¼n giriÅŸ xidmÉ™ti konfiqurasiya edilmÉ™yib.",
  "dashboard.title": "Ä°darÉ™ paneli",
  "dashboard.welcome": "{name} kimi daxil olmusunuz",
  "dashboard.roles": "TÉ™yin edilmiÅŸ rollar",
  "dashboard.noRoles": "Sessiya tÉ™rÉ™findÉ™n rol tÉ™qdim edilmÉ™yib.",
  "navigation.dashboard": "Ä°darÉ™ paneli",
  "navigation.organizations": "TÉ™ÅŸkilat",
  "navigation.stores": "MaÄŸazalar",
  "navigation.products": "MÉ™hsullar",
  "navigation.inventory": "Anbar",
  "navigation.scanner": "Barkod skaneri",
  "navigation.pricing": "QiymÉ™tlÉ™r",
  "navigation.registers": "Kassalar",
  "navigation.reconciliation": "UzlaÅŸdÄ±rma",
  "navigation.customers": "MÃ¼ÅŸtÉ™rilÉ™r",
  "navigation.suppliers": "TÉ™chizatÃ§Ä±lar",
  "navigation.employees": "ÆmÉ™kdaÅŸlar",
  "navigation.purchasing": "SatÄ±nalma",
  "navigation.reports": "Hesabatlar",
  "navigation.stockTransfers": "Anbar transferlÉ™ri",
  "navigation.promotions": "Kampaniyalar",
  "navigation.loyalty": "LoyallÄ±q",
  "navigation.audit": "Audit",
  "management.customers": "MÃ¼ÅŸtÉ™rilÉ™r",
  "management.suppliers": "TÉ™chizatÃ§Ä±lar",
  "management.employees": "ÆmÉ™kdaÅŸlar",
  "management.purchasing": "SatÄ±nalma sifariÅŸlÉ™ri",
  "management.reports": "ÆmÉ™liyyat hesabatÄ±",
  "pricing.title": "QiymÉ™tlÉ™r",
  "pricing.explanation": "Effektiv qiymÉ™tlÉ™ri yoxlayÄ±n vÉ™ icazÉ™li qiymÉ™t dÉ™yiÅŸikliklÉ™rini planlaÅŸdÄ±rÄ±n.",
  "registers.title": "Kassalar",
  "registers.explanation": "Filial kassalarÄ±nÄ± yoxlayÄ±n vÉ™ yeni icazÉ™li kassalar yaradÄ±n.",
  "reconciliation.title": "UzlaÅŸdÄ±rma",
  "reconciliation.explanation": "AÃ§Ä±q vÉ™ baÄŸlanmÄ±ÅŸ nÃ¶vbÉ™lÉ™ri Ã¶dÉ™niÅŸ hadisÉ™lÉ™ri ilÉ™ birlikdÉ™ izlÉ™yin.",
  "reconciliation.trustedBoundary": "NÃ¶vbÉ™ aÃ§Ä±lmasÄ±, naÄŸd pul hÉ™rÉ™kÉ™ti yazÄ±larÄ± vÉ™ nÃ¶vbÉ™ baÄŸlanmasÄ± etibarlÄ± terminal É™mÉ™liyyatlarÄ± olaraq qalÄ±r.",
  "cache.stale": "{time} tarixli oflayn keÅŸ mÉ™lumatÄ±dÄ±r. KÃ¶hnÉ™lmiÅŸ ola bilÉ™r.",
  "apiError.cancelled": "SorÄŸu lÉ™ÄŸv edildi.",
  "apiError.offline": "ServerÉ™ qoÅŸulmaq olmur. BaÄŸlantÄ±nÄ± yoxlayÄ±b yenidÉ™n cÉ™hd edin.",
  "apiError.unauthenticated": "SessiyanÄ±z artÄ±q sÉ™lahiyyÉ™tli deyil. YenidÉ™n daxil olun.",
  "apiError.forbidden": "Bu É™mÉ™liyyat Ã¼Ã§Ã¼n icazÉ™niz yoxdur.",
  "apiError.not_found": "TÉ™lÉ™b olunan qeyd mÃ¶vcud deyil.",
  "apiError.conflict": "Bu É™mÉ™liyyat serverdÉ™ki cari mÉ™lumatla ziddiyyÉ™t tÉ™ÅŸkil edir.",
  "apiError.invalid": "Server gÃ¶ndÉ™rilÉ™n dÉ™yÉ™rlÉ™ri qÉ™bul etmÉ™di.",
  "apiError.unsafe_response": "Server cavabÄ± tÉ™hlÃ¼kÉ™siz ÅŸÉ™kildÉ™ yoxlanÄ±la bilmÉ™di.",
  "apiError.unavailable": "ÆmÉ™liyyat mÃ¼vÉ™qqÉ™ti olaraq É™lÃ§atan deyil.",
  "organizations.title": "TÉ™ÅŸkilat iÅŸ sahÉ™si",
  "organizations.explanation": "Bu sessiya tÉ™hlÃ¼kÉ™siz ÅŸÉ™kildÉ™ bir tÉ™ÅŸkilata baÄŸlÄ±dÄ±r. Cari API tÉ™ÅŸkilat axtarÄ±ÅŸÄ±nÄ± tÉ™qdim etmir.",
  "organizations.current": "Cari tÉ™ÅŸkilat",
  "organizations.chooseStore": "MaÄŸaza seÃ§in",
  "stores.title": "MaÄŸazalar",
  "stores.explanation": "Server Ã¼zvlÃ¼yÃ¼nÃ¼zÃ¼n icazÉ™ verdiyi maÄŸazalardan birini seÃ§in.",
  "stores.empty": "Ä°cazÉ™ verilmiÅŸ konfiqurasiya olunmuÅŸ maÄŸaza qaytarÄ±lmadÄ±.",
  "stores.selected": "SeÃ§ilmiÅŸ iÅŸ sahÉ™si maÄŸazasÄ±",
  "workspace.noBranch": "MaÄŸaza seÃ§ilmÉ™yib.",
  "workspace.branch": "MaÄŸaza: {name}",
  "workspace.branchRequired": "Filial anbarÄ±ndan istifadÉ™ etmÉ™zdÉ™n É™vvÉ™l maÄŸaza seÃ§in.",
  "workspace.chooseBranch": "MaÄŸaza seÃ§in",
  "products.title": "MÉ™hsullar",
  "products.search": "YÃ¼klÉ™nmiÅŸ mÉ™hsullarda axtar",
  "products.searchPlaceholder": "Ad, SKU vÉ™ ya barkod",
  "products.scan": "Barkodu skan et",
  "products.empty": "MÉ™hsul qaytarÄ±lmadÄ±.",
  "products.noMatches": "YÃ¼klÉ™nmiÅŸ mÉ™hsullarda uyÄŸun nÉ™ticÉ™ yoxdur.",
  "products.barcodeNotFound": "Bu barkod Ã¼Ã§Ã¼n mÉ™hsul tapÄ±lmadÄ±.",
  "products.scannedResult": "Skan edilmiÅŸ mÉ™hsul",
  "products.noBarcode": "Barkod yoxdur",
  "products.inactive": "Deaktiv",
  "inventory.title": "Anbar qalÄ±ÄŸÄ±",
  "inventory.empty": "Anbar mÃ¶vqeyi qaytarÄ±lmadÄ±.",
  "inventory.quantity": "Miqdar: {quantity}",
  "inventory.receive": "Mal qÉ™bul et",
  "inventory.adjust": "QalÄ±ÄŸÄ± dÃ¼zÉ™lt",
  "movement.receiptTitle": "Mal qÉ™bulu",
  "movement.adjustmentTitle": "QalÄ±q dÃ¼zÉ™liÅŸi",
  "movement.increase": "ArtÄ±r",
  "movement.decrease": "Azalt",
  "movement.productId": "MÉ™hsul UUID-si",
  "movement.quantity": "Miqdar",
  "movement.reason": "SÉ™bÉ™b (istÉ™yÉ™ baÄŸlÄ±)",
  "movement.onlineOnly": "Bu yazÄ± yalnÄ±z onlayndÄ±r. Oflayn halda nÃ¶vbÉ™yÉ™ alÄ±nmÄ±r vÉ™ sinxronlaÅŸdÄ±rÄ±lmÄ±ÅŸ kimi gÃ¶stÉ™rilmir.",
  "movement.invalid": "DÃ¼zgÃ¼n mÉ™hsul UUID-si, altÄ± onluq rÉ™qÉ™mÉ™ qÉ™dÉ™r mÃ¼sbÉ™t miqdar vÉ™ 200 simvoldan qÄ±sa sÉ™bÉ™b daxil edin.",
  "movement.completed": "Server anbar hÉ™rÉ™kÉ™tini qeydÉ™ aldÄ±.",
  "scanner.title": "Barkod skaneri",
  "scanner.explanation": "Kamera icazÉ™si yalnÄ±z skanÄ± baÅŸladanda istÉ™nilir.",
  "scanner.start": "SkanÄ± baÅŸladÄ±n",
  "scanner.permissionDenied": "Kamera icazÉ™si verilmÉ™di.",
  "scanner.permissionSettings": "Kamera giriÅŸi deaktivdir. Onu sistem ayarlarÄ±nda aktiv edin.",
  "scanner.scanned": "Skan edilmiÅŸ barkod: {value}",
  "scanner.scanAgain": "BaÅŸqa barkod skan edin",
  "scanner.invalidBarcode": "Bu skan dÉ™stÉ™klÉ™nÉ™n rÉ™qÉ™msal mÉ™hsul barkodu deyil.",
};

const ka: TranslationTable = {
  "app.name": "SalekhPos",
  "common.retry": "áƒ®áƒ”áƒšáƒáƒ®áƒšáƒ áƒªáƒ“áƒ",
  "common.back": "áƒ£áƒ™áƒáƒœ",
  "common.loading": "áƒ˜áƒ¢áƒ•áƒ˜áƒ áƒ—áƒ”áƒ‘áƒ",
  "common.loadMore": "áƒ›áƒ”áƒ¢áƒ˜áƒ¡ áƒ©áƒáƒ¢áƒ•áƒ˜áƒ áƒ—áƒ•áƒ",
  "common.save": "áƒ¨áƒ”áƒœáƒáƒ®áƒ•áƒ",
  "common.saving": "áƒ˜áƒœáƒáƒ®áƒ”áƒ‘áƒâ€¦",
  "common.signOut": "áƒ’áƒáƒ¡áƒ•áƒšáƒ",
  "error.title": "áƒ“áƒáƒ¤áƒ˜áƒ¥áƒ¡áƒ˜áƒ áƒ“áƒ áƒ¨áƒ”áƒªáƒ“áƒáƒ›áƒ",
  "error.message": "áƒáƒžáƒšáƒ˜áƒ™áƒáƒªáƒ˜áƒáƒ› áƒ£áƒ¡áƒáƒ¤áƒ áƒ—áƒ®áƒáƒ“ áƒ’áƒáƒ’áƒ áƒ«áƒ”áƒšáƒ”áƒ‘áƒ áƒ•áƒ”áƒ  áƒ¨áƒ”áƒ«áƒšáƒ.",
  "config.title": "áƒ¡áƒáƒ­áƒ˜áƒ áƒáƒ áƒ™áƒáƒœáƒ¤áƒ˜áƒ’áƒ£áƒ áƒáƒªáƒ˜áƒ",
  "config.message": "áƒ¨áƒ”áƒ¡áƒ•áƒšáƒáƒ›áƒ“áƒ” áƒ›áƒ˜áƒ£áƒ—áƒ˜áƒ—áƒ”áƒ— áƒ¡áƒ¬áƒáƒ áƒ˜ API áƒ’áƒáƒ áƒ”áƒ›áƒ áƒ“áƒ áƒ¡áƒáƒ‘áƒáƒ–áƒ˜áƒ¡áƒ URL.",
  "session.restoreError": "áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ“áƒáƒªáƒ£áƒšáƒ˜ áƒ¡áƒ”áƒ¡áƒ˜áƒ˜áƒ¡ áƒáƒ¦áƒ“áƒ’áƒ”áƒœáƒ áƒ•áƒ”áƒ  áƒ›áƒáƒ®áƒ”áƒ áƒ®áƒ“áƒ.",
  "signIn.title": "áƒ£áƒ¡áƒáƒ¤áƒ áƒ—áƒ®áƒ áƒ¨áƒ”áƒ¡áƒ•áƒšáƒ",
  "signIn.message": "áƒ’áƒáƒ¡áƒáƒ’áƒ áƒ«áƒ”áƒšáƒ”áƒ‘áƒšáƒáƒ“ áƒ’áƒáƒ›áƒáƒ˜áƒ§áƒ”áƒœáƒ”áƒ— áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒ˜áƒ¡ áƒ“áƒáƒ›áƒ¢áƒ™áƒ˜áƒªáƒ”áƒ‘áƒ£áƒšáƒ˜ áƒáƒ•áƒ¢áƒáƒ áƒ˜áƒ–áƒáƒªáƒ˜áƒ.",
  "signIn.pending": "áƒáƒ› áƒ•áƒ”áƒ áƒ¡áƒ˜áƒ˜áƒ¡áƒ—áƒ•áƒ˜áƒ¡ áƒáƒ•áƒ¢áƒáƒ áƒ˜áƒ–áƒáƒªáƒ˜áƒ˜áƒ¡ áƒžáƒ áƒáƒ•áƒáƒ˜áƒ“áƒ”áƒ áƒ˜ áƒ™áƒáƒœáƒ¤áƒ˜áƒ’áƒ£áƒ áƒ˜áƒ áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒáƒ  áƒáƒ áƒ˜áƒ¡.",
  "dashboard.title": "áƒ›áƒáƒ áƒ—áƒ•áƒ˜áƒ¡ áƒžáƒáƒœáƒ”áƒšáƒ˜",
  "dashboard.welcome": "áƒ¨áƒ”áƒ¡áƒ£áƒšáƒ˜ áƒ®áƒáƒ áƒ— áƒ áƒáƒ’áƒáƒ áƒª {name}",
  "dashboard.roles": "áƒ›áƒ˜áƒœáƒ˜áƒ­áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ áƒáƒšáƒ”áƒ‘áƒ˜",
  "dashboard.noRoles": "áƒ¡áƒ”áƒ¡áƒ˜áƒáƒ¡ áƒ áƒáƒšáƒ”áƒ‘áƒ˜ áƒáƒ  áƒ›áƒáƒ°áƒ§áƒáƒšáƒ˜áƒ.",
  "navigation.dashboard": "áƒ›áƒáƒ áƒ—áƒ•áƒ˜áƒ¡ áƒžáƒáƒœáƒ”áƒšáƒ˜",
  "navigation.organizations": "áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒ",
  "navigation.stores": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ”áƒ‘áƒ˜",
  "navigation.products": "áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ”áƒ‘áƒ˜",
  "navigation.inventory": "áƒ›áƒáƒ áƒáƒ’áƒ”áƒ‘áƒ˜",
  "navigation.scanner": "áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜áƒ¡ áƒ¡áƒ™áƒáƒœáƒ”áƒ áƒ˜",
  "navigation.pricing": "áƒ¤áƒáƒ¡áƒ”áƒ‘áƒ˜",
  "navigation.registers": "áƒ¡áƒáƒšáƒáƒ áƒáƒ”áƒ‘áƒ˜",
  "navigation.reconciliation": "áƒ¨áƒ”áƒ¯áƒ”áƒ áƒ”áƒ‘áƒ",
  "navigation.customers": "áƒ™áƒšáƒ˜áƒ”áƒœáƒ¢áƒ”áƒ‘áƒ˜",
  "navigation.suppliers": "áƒ›áƒáƒ›áƒ¬áƒáƒ“áƒ”áƒ‘áƒšáƒ”áƒ‘áƒ˜",
  "navigation.employees": "áƒ—áƒáƒœáƒáƒ›áƒ¨áƒ áƒáƒ›áƒšáƒ”áƒ‘áƒ˜",
  "navigation.purchasing": "áƒ¨áƒ”áƒ¡áƒ§áƒ˜áƒ“áƒ•áƒ”áƒ‘áƒ˜",
  "navigation.reports": "áƒáƒœáƒ’áƒáƒ áƒ˜áƒ¨áƒ”áƒ‘áƒ˜",
  "navigation.stockTransfers": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ¢áƒ áƒáƒœáƒ¡áƒ¤áƒ”áƒ áƒ”áƒ‘áƒ˜",
  "navigation.promotions": "áƒáƒ¥áƒªáƒ˜áƒ”áƒ‘áƒ˜",
  "navigation.loyalty": "áƒšáƒáƒ˜áƒáƒšáƒáƒ‘áƒ",
  "navigation.audit": "Audit",
  "management.customers": "áƒ™áƒšáƒ˜áƒ”áƒœáƒ¢áƒ”áƒ‘áƒ˜",
  "management.suppliers": "áƒ›áƒáƒ›áƒ¬áƒáƒ“áƒ”áƒ‘áƒšáƒ”áƒ‘áƒ˜",
  "management.employees": "áƒ—áƒáƒœáƒáƒ›áƒ¨áƒ áƒáƒ›áƒšáƒ”áƒ‘áƒ˜",
  "management.purchasing": "áƒ¨áƒ”áƒ¡áƒ§áƒ˜áƒ“áƒ•áƒ˜áƒ¡ áƒ¨áƒ”áƒ™áƒ•áƒ”áƒ—áƒ”áƒ‘áƒ˜",
  "management.reports": "áƒáƒžáƒ”áƒ áƒáƒªáƒ˜áƒ£áƒšáƒ˜ áƒáƒœáƒ’áƒáƒ áƒ˜áƒ¨áƒ˜",
  "pricing.title": "áƒ¤áƒáƒ¡áƒ”áƒ‘áƒ˜",
  "pricing.explanation": "áƒ¨áƒ”áƒáƒ›áƒáƒ¬áƒ›áƒ”áƒ— áƒ›áƒáƒ¥áƒ›áƒ”áƒ“áƒ˜ áƒ¤áƒáƒ¡áƒ”áƒ‘áƒ˜ áƒ“áƒ áƒ“áƒáƒ’áƒ”áƒ’áƒ›áƒ”áƒ— áƒáƒ•áƒ¢áƒáƒ áƒ˜áƒ–áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒªáƒ•áƒšáƒ˜áƒšáƒ”áƒ‘áƒ”áƒ‘áƒ˜.",
  "registers.title": "áƒ¡áƒáƒšáƒáƒ áƒáƒ”áƒ‘áƒ˜",
  "registers.explanation": "áƒ˜áƒ®áƒ˜áƒšáƒ”áƒ— áƒ¤áƒ˜áƒšáƒ˜áƒáƒšáƒ˜áƒ¡ áƒ¡áƒáƒšáƒáƒ áƒáƒ”áƒ‘áƒ˜ áƒ“áƒ áƒ¨áƒ”áƒ¥áƒ›áƒ”áƒœáƒ˜áƒ— áƒáƒ®áƒáƒšáƒ˜ áƒáƒ•áƒ¢áƒáƒ áƒ˜áƒ–áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ¡áƒáƒšáƒáƒ áƒáƒ”áƒ‘áƒ˜.",
  "reconciliation.title": "áƒ¨áƒ”áƒ¯áƒ”áƒ áƒ”áƒ‘áƒ",
  "reconciliation.explanation": "áƒáƒ™áƒáƒœáƒ¢áƒ áƒáƒšáƒ”áƒ— áƒ¦áƒ˜áƒ áƒ“áƒ áƒ“áƒáƒ®áƒ£áƒ áƒ£áƒšáƒ˜ áƒªáƒ•áƒšáƒ”áƒ‘áƒ˜ áƒ’áƒáƒ“áƒáƒ®áƒ“áƒ˜áƒ¡ áƒ›áƒáƒ•áƒšáƒ”áƒœáƒ”áƒ‘áƒ—áƒáƒœ áƒ”áƒ áƒ—áƒáƒ“.",
  "reconciliation.trustedBoundary": "áƒªáƒ•áƒšáƒ˜áƒ¡ áƒ’áƒáƒ®áƒ¡áƒœáƒ, áƒœáƒáƒ¦áƒ“áƒ˜ áƒ¤áƒ£áƒšáƒ˜áƒ¡ áƒ›áƒáƒ«áƒ áƒáƒáƒ‘áƒ˜áƒ¡ áƒ©áƒáƒ¬áƒ”áƒ áƒ áƒ“áƒ áƒªáƒ•áƒšáƒ˜áƒ¡ áƒ“áƒáƒ®áƒ£áƒ áƒ•áƒ áƒ áƒ©áƒ”áƒ‘áƒ áƒ¡áƒáƒœáƒ“áƒ áƒ¢áƒ”áƒ áƒ›áƒ˜áƒœáƒáƒšáƒ˜áƒ¡ áƒáƒžáƒ”áƒ áƒáƒªáƒ˜áƒ”áƒ‘áƒáƒ“.",
  "cache.stale": "áƒáƒ¤áƒšáƒáƒ˜áƒœ áƒ¥áƒ”áƒ¨áƒ˜áƒ¡ áƒ›áƒáƒœáƒáƒªáƒ”áƒ›áƒ”áƒ‘áƒ˜ {time}-áƒ“áƒáƒœ. áƒ¨áƒ”áƒ¡áƒáƒ«áƒšáƒáƒ áƒ›áƒáƒ«áƒ•áƒ”áƒšáƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ˜áƒ§áƒáƒ¡.",
  "apiError.cancelled": "áƒ›áƒáƒ—áƒ®áƒáƒ•áƒœáƒ áƒ’áƒáƒ£áƒ¥áƒ›áƒ“áƒ.",
  "apiError.offline": "áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ—áƒáƒœ áƒ“áƒáƒ™áƒáƒ•áƒ¨áƒ˜áƒ áƒ”áƒ‘áƒ áƒ•áƒ”áƒ  áƒ®áƒ”áƒ áƒ®áƒ“áƒ”áƒ‘áƒ. áƒ¨áƒ”áƒáƒ›áƒáƒ¬áƒ›áƒ”áƒ— áƒ™áƒáƒ•áƒ¨áƒ˜áƒ áƒ˜ áƒ“áƒ áƒ¡áƒªáƒáƒ“áƒ”áƒ— áƒ™áƒ•áƒšáƒáƒ•.",
  "apiError.unauthenticated": "áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ¡áƒ”áƒ¡áƒ˜áƒ áƒáƒ¦áƒáƒ  áƒáƒ áƒ˜áƒ¡ áƒáƒ•áƒ¢áƒáƒ áƒ˜áƒ–áƒ”áƒ‘áƒ£áƒšáƒ˜. áƒ¨áƒ”áƒ“áƒ˜áƒ— áƒ—áƒáƒ•áƒ˜áƒ“áƒáƒœ.",
  "apiError.forbidden": "áƒáƒ› áƒáƒžáƒ”áƒ áƒáƒªáƒ˜áƒ˜áƒ¡ áƒœáƒ”áƒ‘áƒáƒ áƒ—áƒ•áƒ áƒáƒ  áƒ’áƒáƒ¥áƒ•áƒ—.",
  "apiError.not_found": "áƒ›áƒáƒ—áƒ®áƒáƒ•áƒœáƒ˜áƒšáƒ˜ áƒ©áƒáƒœáƒáƒ¬áƒ”áƒ áƒ˜ áƒ›áƒ˜áƒ£áƒ¬áƒ•áƒ“áƒáƒ›áƒ”áƒšáƒ˜áƒ.",
  "apiError.conflict": "áƒáƒžáƒ”áƒ áƒáƒªáƒ˜áƒ áƒ”áƒ¬áƒ˜áƒœáƒáƒáƒ¦áƒ›áƒ“áƒ”áƒ’áƒ”áƒ‘áƒ áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ˜áƒ¡ áƒ›áƒ˜áƒ›áƒ“áƒ˜áƒœáƒáƒ áƒ” áƒ›áƒáƒœáƒáƒªáƒ”áƒ›áƒ”áƒ‘áƒ¡.",
  "apiError.invalid": "áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ›áƒ áƒ’áƒáƒ’áƒ–áƒáƒ•áƒœáƒ˜áƒšáƒ˜ áƒ›áƒœáƒ˜áƒ¨áƒ•áƒœáƒ”áƒšáƒáƒ‘áƒ”áƒ‘áƒ˜ áƒ£áƒáƒ áƒ§áƒ.",
  "apiError.unsafe_response": "áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ˜áƒ¡ áƒžáƒáƒ¡áƒ£áƒ®áƒ˜áƒ¡ áƒ£áƒ¡áƒáƒ¤áƒ áƒ—áƒ®áƒáƒ“ áƒ’áƒáƒ“áƒáƒ›áƒáƒ¬áƒ›áƒ”áƒ‘áƒ áƒ•áƒ”áƒ  áƒ›áƒáƒ®áƒ”áƒ áƒ®áƒ“áƒ.",
  "apiError.unavailable": "áƒáƒžáƒ”áƒ áƒáƒªáƒ˜áƒ áƒ“áƒ áƒáƒ”áƒ‘áƒ˜áƒ— áƒ›áƒ˜áƒ£áƒ¬áƒ•áƒ“áƒáƒ›áƒ”áƒšáƒ˜áƒ.",
  "organizations.title": "áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒ˜áƒ¡ áƒ¡áƒáƒ›áƒ£áƒ¨áƒáƒ áƒ¡áƒ˜áƒ•áƒ áƒªáƒ”",
  "organizations.explanation": "áƒ”áƒ¡ áƒ¡áƒ”áƒ¡áƒ˜áƒ áƒ£áƒ¡áƒáƒ¤áƒ áƒ—áƒ®áƒáƒ“ áƒáƒ áƒ˜áƒ¡ áƒ›áƒ˜áƒ‘áƒ›áƒ£áƒšáƒ˜ áƒ”áƒ áƒ— áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒáƒ–áƒ”. áƒ›áƒ˜áƒ›áƒ“áƒ˜áƒœáƒáƒ áƒ” API áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒ”áƒ‘áƒ˜áƒ¡ áƒ›áƒáƒ«áƒ˜áƒ”áƒ‘áƒáƒ¡ áƒáƒ  áƒ£áƒ–áƒ áƒ£áƒœáƒ•áƒ”áƒšáƒ§áƒáƒ¤áƒ¡.",
  "organizations.current": "áƒ›áƒ˜áƒ›áƒ“áƒ˜áƒœáƒáƒ áƒ” áƒáƒ áƒ’áƒáƒœáƒ˜áƒ–áƒáƒªáƒ˜áƒ",
  "organizations.chooseStore": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ˜áƒ¡ áƒáƒ áƒ©áƒ”áƒ•áƒ",
  "stores.title": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ”áƒ‘áƒ˜",
  "stores.explanation": "áƒáƒ˜áƒ áƒ©áƒ˜áƒ”áƒ— áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ–áƒ” áƒ—áƒ¥áƒ•áƒ”áƒœáƒ˜ áƒ¬áƒ”áƒ•áƒ áƒáƒ‘áƒ˜áƒ— áƒ“áƒáƒ¨áƒ•áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ.",
  "stores.empty": "áƒ“áƒáƒ¨áƒ•áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ“áƒ áƒ™áƒáƒœáƒ¤áƒ˜áƒ’áƒ£áƒ áƒ˜áƒ áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ áƒáƒ  áƒ“áƒáƒ‘áƒ áƒ£áƒœáƒ”áƒ‘áƒ£áƒšáƒ.",
  "stores.selected": "áƒáƒ áƒ©áƒ”áƒ£áƒšáƒ˜ áƒ¡áƒáƒ›áƒ£áƒ¨áƒáƒ áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ",
  "workspace.noBranch": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ áƒáƒ áƒ©áƒ”áƒ£áƒšáƒ˜ áƒáƒ  áƒáƒ áƒ˜áƒ¡.",
  "workspace.branch": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ: {name}",
  "workspace.branchRequired": "áƒ¤áƒ˜áƒšáƒ˜áƒáƒšáƒ˜áƒ¡ áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ’áƒáƒ›áƒáƒ§áƒ”áƒœáƒ”áƒ‘áƒáƒ›áƒ“áƒ” áƒáƒ˜áƒ áƒ©áƒ˜áƒ”áƒ— áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ.",
  "workspace.chooseBranch": "áƒ›áƒáƒ¦áƒáƒ–áƒ˜áƒ˜áƒ¡ áƒáƒ áƒ©áƒ”áƒ•áƒ",
  "products.title": "áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ”áƒ‘áƒ˜",
  "products.search": "áƒ©áƒáƒ¢áƒ•áƒ˜áƒ áƒ—áƒ£áƒš áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ”áƒ‘áƒ¨áƒ˜ áƒ«áƒ”áƒ‘áƒœáƒ",
  "products.searchPlaceholder": "áƒ¡áƒáƒ®áƒ”áƒšáƒ˜, SKU áƒáƒœ áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜",
  "products.scan": "áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜áƒ¡ áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ",
  "products.empty": "áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ”áƒ‘áƒ˜ áƒáƒ  áƒ“áƒáƒ‘áƒ áƒ£áƒœáƒ”áƒ‘áƒ£áƒšáƒ.",
  "products.noMatches": "áƒ©áƒáƒ¢áƒ•áƒ˜áƒ áƒ—áƒ£áƒš áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ”áƒ‘áƒ¨áƒ˜ áƒ“áƒáƒ›áƒ—áƒ®áƒ•áƒ”áƒ•áƒ áƒáƒ  áƒáƒ áƒ˜áƒ¡.",
  "products.barcodeNotFound": "áƒáƒ› áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜áƒ— áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ˜ áƒ•áƒ”áƒ  áƒ›áƒáƒ˜áƒ«áƒ”áƒ‘áƒœáƒ.",
  "products.scannedResult": "áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ˜",
  "products.noBarcode": "áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜ áƒáƒ  áƒáƒ¥áƒ•áƒ¡",
  "products.inactive": "áƒáƒ áƒáƒáƒ¥áƒ¢áƒ˜áƒ£áƒ áƒ˜",
  "inventory.title": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒœáƒáƒ¨áƒ—áƒ˜",
  "inventory.empty": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ©áƒáƒœáƒáƒ¬áƒ”áƒ áƒ”áƒ‘áƒ˜ áƒáƒ  áƒ“áƒáƒ‘áƒ áƒ£áƒœáƒ”áƒ‘áƒ£áƒšáƒ.",
  "inventory.quantity": "áƒ áƒáƒáƒ“áƒ”áƒœáƒáƒ‘áƒ: {quantity}",
  "inventory.receive": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ›áƒ˜áƒ¦áƒ”áƒ‘áƒ",
  "inventory.adjust": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ™áƒáƒ áƒ”áƒ¥áƒ¢áƒ˜áƒ áƒ”áƒ‘áƒ",
  "movement.receiptTitle": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ›áƒ˜áƒ¦áƒ”áƒ‘áƒ",
  "movement.adjustmentTitle": "áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ™áƒáƒ áƒ”áƒ¥áƒ¢áƒ˜áƒ áƒ”áƒ‘áƒ",
  "movement.increase": "áƒ’áƒáƒ–áƒ áƒ“áƒ",
  "movement.decrease": "áƒ¨áƒ”áƒ›áƒªáƒ˜áƒ áƒ”áƒ‘áƒ",
  "movement.productId": "áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ˜áƒ¡ UUID",
  "movement.quantity": "áƒ áƒáƒáƒ“áƒ”áƒœáƒáƒ‘áƒ",
  "movement.reason": "áƒ›áƒ˜áƒ–áƒ”áƒ–áƒ˜ (áƒáƒ áƒáƒ¡áƒáƒ•áƒáƒšáƒ“áƒ”áƒ‘áƒ£áƒšáƒ)",
  "movement.onlineOnly": "áƒ”áƒ¡ áƒ©áƒáƒ¬áƒ”áƒ áƒ áƒ›áƒ®áƒáƒšáƒáƒ“ áƒáƒœáƒšáƒáƒ˜áƒœ áƒ›áƒ£áƒ¨áƒáƒáƒ‘áƒ¡. áƒáƒ¤áƒšáƒáƒ˜áƒœ áƒ áƒ”áƒŸáƒ˜áƒ›áƒ¨áƒ˜ áƒ áƒ˜áƒ’áƒ¨áƒ˜ áƒáƒ  áƒ“áƒ’áƒ”áƒ‘áƒ áƒ“áƒ áƒ¡áƒ˜áƒœáƒ¥áƒ áƒáƒœáƒ˜áƒ–áƒ”áƒ‘áƒ£áƒšáƒáƒ“ áƒáƒ  áƒáƒ áƒ˜áƒ¡ áƒœáƒáƒ©áƒ•áƒ”áƒœáƒ”áƒ‘áƒ˜.",
  "movement.invalid": "áƒ¨áƒ”áƒ˜áƒ§áƒ•áƒáƒœáƒ”áƒ— áƒ¡áƒ¬áƒáƒ áƒ˜ áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ˜áƒ¡ UUID, áƒ“áƒáƒ“áƒ”áƒ‘áƒ˜áƒ—áƒ˜ áƒ áƒáƒáƒ“áƒ”áƒœáƒáƒ‘áƒ áƒ›áƒáƒ¥áƒ¡áƒ˜áƒ›áƒ£áƒ› áƒ”áƒ¥áƒ•áƒ¡áƒ˜ áƒáƒ—áƒ¬áƒ˜áƒšáƒáƒ“áƒ˜áƒ— áƒ“áƒ 200 áƒ¡áƒ˜áƒ›áƒ‘áƒáƒšáƒáƒ–áƒ” áƒ›áƒáƒ™áƒšáƒ” áƒ›áƒ˜áƒ–áƒ”áƒ–áƒ˜.",
  "movement.completed": "áƒ¡áƒ”áƒ áƒ•áƒ”áƒ áƒ›áƒ áƒ›áƒáƒ áƒáƒ’áƒ˜áƒ¡ áƒ›áƒáƒ«áƒ áƒáƒáƒ‘áƒ áƒ©áƒáƒ¬áƒ”áƒ áƒ.",
  "scanner.title": "áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜áƒ¡ áƒ¡áƒ™áƒáƒœáƒ”áƒ áƒ˜",
  "scanner.explanation": "áƒ™áƒáƒ›áƒ”áƒ áƒ˜áƒ¡ áƒœáƒ”áƒ‘áƒáƒ áƒ—áƒ•áƒ áƒ›áƒáƒ˜áƒ—áƒ®áƒáƒ•áƒ”áƒ‘áƒ áƒ›áƒ®áƒáƒšáƒáƒ“ áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ˜áƒ¡ áƒ“áƒáƒ¬áƒ§áƒ”áƒ‘áƒ˜áƒ¡áƒáƒ¡.",
  "scanner.start": "áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ˜áƒ¡ áƒ“áƒáƒ¬áƒ§áƒ”áƒ‘áƒ",
  "scanner.permissionDenied": "áƒ™áƒáƒ›áƒ”áƒ áƒ˜áƒ¡ áƒœáƒ”áƒ‘áƒáƒ áƒ—áƒ•áƒ áƒáƒ  áƒ’áƒáƒ˜áƒªáƒ.",
  "scanner.permissionSettings": "áƒ™áƒáƒ›áƒ”áƒ áƒáƒ–áƒ” áƒ¬áƒ•áƒ“áƒáƒ›áƒ áƒ’áƒáƒ›áƒáƒ áƒ—áƒ£áƒšáƒ˜áƒ. áƒ©áƒáƒ áƒ—áƒ”áƒ— áƒ¡áƒ˜áƒ¡áƒ¢áƒ”áƒ›áƒ˜áƒ¡ áƒžáƒáƒ áƒáƒ›áƒ”áƒ¢áƒ áƒ”áƒ‘áƒ¨áƒ˜.",
  "scanner.scanned": "áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ£áƒšáƒ˜ áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜: {value}",
  "scanner.scanAgain": "áƒ¡áƒ®áƒ•áƒ áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜áƒ¡ áƒ¡áƒ™áƒáƒœáƒ˜áƒ áƒ”áƒ‘áƒ",
  "scanner.invalidBarcode": "áƒ”áƒ¡ áƒ¡áƒ™áƒáƒœáƒ˜ áƒ›áƒ®áƒáƒ áƒ“áƒáƒ­áƒ”áƒ áƒ˜áƒšáƒ˜ áƒªáƒ˜áƒ¤áƒ áƒ£áƒšáƒ˜ áƒžáƒ áƒáƒ“áƒ£áƒ¥áƒ¢áƒ˜áƒ¡ áƒ¨áƒ¢áƒ áƒ˜áƒ®áƒ™áƒáƒ“áƒ˜ áƒáƒ  áƒáƒ áƒ˜áƒ¡.",
};

export const resources: Readonly<Record<SupportedLocale, TranslationTable>> = {
  en,
  az,
  ka,
};

export function translate(
  locale: SupportedLocale,
  key: TranslationKey,
  values: Readonly<Record<string, string>> = {},
): string {
  const template = resources[locale][key] ?? resources.en[key];
  return template.replace(/\{(\w+)\}/gu, (_, name: string) => values[name] ?? `{${name}}`);
}
