<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="../SalekhPos.Taxation.Application/SalekhPos.Taxation.Application.csproj" /><ProjectReference Include="../SalekhPos.Taxation.Contracts/SalekhPos.Taxation.Contracts.csproj" /></ItemGroup></Project>
