<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="../SalekhPos.Notifications.Application/SalekhPos.Notifications.Application.csproj" /><ProjectReference Include="../SalekhPos.Notifications.Contracts/SalekhPos.Notifications.Contracts.csproj" /></ItemGroup></Project>
