<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Reporting.Application/SalekhPos.Reporting.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Reporting.Contracts/SalekhPos.Reporting.Contracts.csproj" />
    <ProjectReference Include="../SalekhPos.Reporting.Domain/SalekhPos.Reporting.Domain.csproj" />
  </ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
