<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SalekhPos.Promotions.Application/SalekhPos.Promotions.Application.csproj" />
    <ProjectReference Include="../SalekhPos.Promotions.Domain/SalekhPos.Promotions.Domain.csproj" />
    <ProjectReference Include="../SalekhPos.Promotions.Contracts/SalekhPos.Promotions.Contracts.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
